In [ ]:
import pandas as pd
from google.colab import sheets

file_path = '/content/drive/MyDrive/SIC_Code_5521.csv'
sic5521 = pd.read_csv(file_path)
sic5521

,Company Name,Address,City,State,Zip,County,Phone,Contact First,Contact Last,Title,Direct Phone,Email,Website,Employee Range,Annual Sales,SIC Code,Industry
0,R C Foster Truck Sales,1200 W Troy Ave,Indianapolis,IN,46225-2250,Marion,3.177872e+09,William,Foster,President,NaN,bdf@fosterstruck.com,fosterstruck.com,5 To 9,$2.5 To 5 Million,552101,Truck-dealers-used
1,Newark Truck & Tractor,4295 W Us Route 6,Morris,IL,60450-8855,Grundy,8.159425e+09,Bennie,Helland,President,NaN,bhelland@newarktruckandtractor.com,newarktruckandtractor.com,5 To 9,$5 To 10 Million,552101,Truck-dealers-used
2,Munday Truck Sales & Svc,8161 State Road 33 N,Lakeland,FL,33809-1706,Polk,8.639843e+09,Dennis,Munday,President,NaN,dennismunday@mundaymachinery.com,NaN,1 To 4,"$500,000 To $1 Million",552101,Truck-dealers-used
3,Redline Automotive Inc,5901 Sw 43rd St Ste 4,Fort Lauderdale,FL,33314-3635,Broward,9.547924e+09,Rich,Jones,Owner,NaN,rich.jones@redlineauto.net,NaN,1 To 4,$1 To 2.5 Million,552103,Automobile Racing Cars
4,Truck Country,10930 Limonite Ave,Mira Loma,CA,91752-2255,Riverside,9.517350e+09,Erik,Thomas,Director - Human Resources,5635842622,erikthoms@truckcountry.com,NaN,1 To 4,$1 To 2.5 Million,552101,Truck-dealers-used
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8407,Midwest Truck Auto Sales,420 S Dirksen Pkwy,Springfield,IL,62703-2107,Sangamon,2.177530e+09,Russell,Wake,President,NaN,russell.wake@midwest-truck-sales.com,midwest-truck-sales.com,5 To 9,$2.5 To 5 Million,552101,Truck-dealers-used
8408,Tnt Enterprise,35547 Grandview Dr,Yucaipa,CA,92399-4432,San Bernardino,9.097973e+09,Donta,Montgomery,Principal,NaN,donta.montgomery@tntenterprises.us,NaN,1 To 4,$1 To 2.5 Million,552103,Automobile Racing Cars
8409,Metropolitan Pit Stop Inc,5324 Laurel Canyon Blvd,Valley Village,CA,91607-2712,Los Angeles,8.187692e+09,Justin,Barsony,Vice President Of Operations,NaN,justin@metpitstop.com,metpitstop.com,5 To 9,$2.5 To 5 Million,552102,Automobile-antique & Classic
8410,Stanek Automotive,401 5th St,Malcom,IA,50157,Poweshiek,6.415284e+09,Terry,Stanek,Owner,NaN,tstanek@iowatelecom.net,NaN,1 To 4,"$500,000 To $1 Million",552102,Automobile-antique & Classic
8411,Frye Motor Sports,66 Pinnacle Springs Rd,Greenbrier,AR,72058,Faulkner,5.016797e+09,Bill,Frye,Chief Executive Officer,NaN,bill@billfrye.com,billfrye.com,1 To 4,"$500,000 To $1 Million",552103,Automobile Racing Cars

In [ ]:
#generate excel in colab
sheet = sheets.InteractiveSheet(df=sic5521)

https://docs.google.com/spreadsheets/d/1yCkWvKsgBuWUo4tKgB42dc-ty1KTocINxuUC8vwB7-g#gid=0

##Data Exploration

In [ ]:
#Check data type and null values of each column
def column_describe(df):
    data = []
    for column in df.columns:
      data.append([
                  column, \
                  df[column].dtype, \
                  df[column].notna().sum(), \
                  df[column].isna().sum(), \
                  f"{round(100*(df[column].isna().sum()/len(df)),2)}%", \
                  df[column].nunique()
                  ])
    return pd.DataFrame(columns=['Column Names','Data Type','# of Not Null Value','# of Null Value','Null Value Percentage','# of Unique Value'], data=data)

column_describe(sic5521)

,Column Names,Data Type,# of Not Null Value,# of Null Value,Null Value Percentage,# of Unique Value
0,Company Name,object,8412,0,0.0%,2547
1,Address,object,8312,100,1.19%,2685
2,City,object,8402,10,0.12%,1526
3,State,object,8402,10,0.12%,48
4,Zip,object,8402,10,0.12%,2683
5,County,object,8303,109,1.3%,697
6,Phone,float64,8352,60,0.71%,2684
7,Contact First,object,7628,784,9.32%,1410
8,Contact Last,object,7739,673,8.0%,4019
9,Title,object,5594,2818,33.5%,1145
10,Direct Phone,object,1326,7086,84.24%,836
11,Email,object,8412,0,0.0%,7008
12,Website,object,7419,993,11.8%,1775
13,Employee Range,object,6712,1700,20.21%,8
14,Annual Sales,object,6673,1739,20.67%,11
15,SIC Code,int64,8412,0,0.0%,6
16,Industry,object,8412,0,0.0%,13

Company Name: The name of the company\
Address: Detailed address including house number and street name\
City: the city where the company is located.\
State: the state where the company is located.\
Zip: the zip code of where the company is located.\
County: the county where the company is located.\
Phone: Usually the office phone or boss's phone\
Contact First: First name of the contact person\
Contact Last: Last name of the contact person\
Title: Title of the contact person\
Direct Phone: The direct phone of the contact person\
Email: Usually the personal email of the contact person\
Website: The website of the company\
Employee Range: Estimated employee size\
Annual Sales: Estimated annual Sales\
SIC Code: The six-digit SIC code affiliated with 5521\
Industry: The industry name of the six-digit SIC code

##Find out SIC Codes and corresponds Industries

In [ ]:
#Count the number of unique SIC Codes and Industry names
num_sic_code = sic5521['SIC Code'].nunique()
num_industry = sic5521['Industry'].nunique()

#List the unique SIC Codes and Industry names
unique_sic_code = sic5521['SIC Code'].unique()
unique_industry = sic5521['Industry'].unique()

print(f"There are {num_sic_code} different SIC Codes")
print(f"There are {num_industry} different Industry names")
print(f"They are: {unique_sic_code}")
print(f"They are: {unique_industry}")

#Showing the distribution of values in the "SIC Code" column
def col_dist(df):
  return df['SIC Code'].value_counts()
col_dist(sic5521)

There are 6 different SIC Codes
There are 13 different Industry names
They are: [552101 552103 552102 552199 552100 552198]
They are: ['Truck-dealers-used' 'Automobile Racing Cars'
 'Automobile-antique & Classic' 'Ret Used Automobiles' 'Used Car Dealers'
 'Motor Vehicle Dealers-used Only' 'Automobile Dealers Performance & Race'
 'Automobiles, Used Cars Only' 'Motor Vehicle Dealers (used Only)'
 'Trucks, Tractors, And Trailers: Used' 'Used Car Dealers; Nec'
 'Used Car Dealers, Nec' 'Used Car Dealers, Nec,5521-9902,automobiles']

SIC Code
552101    3005
552103    2180
552102    1550
552199     862
552100     634
552198     181
Name: count, dtype: int64

![image.png]()

In [ ]:
#Group by SIC Code and aggregate industries
sic_to_industries = sic5521.groupby('SIC Code')['Industry'].unique()

#Convert to df
sic_to_industries_df = sic_to_industries.reset_index()

#Filter to only show one SIC Code at a time
sic_552100 = sic_to_industries_df[sic_to_industries_df['SIC Code'] == 552100]
sic_552101 = sic_to_industries_df[sic_to_industries_df['SIC Code'] == 552101]
sic_552102 = sic_to_industries_df[sic_to_industries_df['SIC Code'] == 552102]
sic_552103 = sic_to_industries_df[sic_to_industries_df['SIC Code'] == 552103]
sic_552198 = sic_to_industries_df[sic_to_industries_df['SIC Code'] == 552198]
sic_552199 = sic_to_industries_df[sic_to_industries_df['SIC Code'] == 552199]

#Show all text
pd.set_option('display.max_colwidth', None)

sic_to_industries_df

,SIC Code,Industry
0,552100,"[Used Car Dealers, Motor Vehicle Dealers (used Only)]"
1,552101,"[Truck-dealers-used, Used Car Dealers]"
2,552102,"[Automobile-antique & Classic, Used Car Dealers]"
3,552103,"[Automobile Racing Cars, Used Car Dealers, Automobile Dealers Performance & Race]"
4,552198,"[Motor Vehicle Dealers-used Only, Used Car Dealers]"
5,552199,"[Ret Used Automobiles, Automobiles, Used Cars Only, Trucks, Tractors, And Trailers: Used, Used Car Dealers; Nec, Used Car Dealers, Nec, Used Car Dealers, Nec,5521-9902,automobiles]"

###SIC codes

####552100

In [ ]:
sic_552100

   SIC Code                                               Industry
0    552100  [Used Car Dealers, Motor Vehicle Dealers (used Only)]

####552101

In [ ]:
sic_552101

   SIC Code                                Industry
1    552101  [Truck-dealers-used, Used Car Dealers]

####552102

In [ ]:
sic_552102

   SIC Code                                          Industry
2    552102  [Automobile-antique & Classic, Used Car Dealers]

####552103

In [ ]:
sic_552103

,SIC Code,Industry
3,552103,"[Automobile Racing Cars, Used Car Dealers, Automobile Dealers Performance & Race]"

####552198

In [ ]:
sic_552198

   SIC Code                                             Industry
4    552198  [Motor Vehicle Dealers-used Only, Used Car Dealers]

####552199

In [ ]:
sic_552199

,SIC Code,Industry
5,552199,"[Ret Used Automobiles, Automobiles, Used Cars Only, Trucks, Tractors, And Trailers: Used, Used Car Dealers; Nec, Used Car Dealers, Nec, Used Car Dealers, Nec,5521-9902,automobiles]"

Ret Used Automobiles\
Automobiles, Used Cars Only, \
Trucks, Tractors, And Trailers: Used,\
Used Car Dealers; Nec\
Used Car Dealers, Nec\
Used Car Dealers, Nec,5521-9902,automobiles

##Find out misspellings

In [ ]:
#the function to show the distribution of a certain column
def col_dist(column):
  return sic5521[column].value_counts()

#the function to count how many unique values in a certain column
def uniq_value(column):
  uniq = sic5521[column].nunique()
  return print(f"There are {uniq} different values in the {column} column")

#the function to list out unique values in a certain column(not include null values)
def sorted_unique(column):
  unique = sorted(sic5521[column].dropna().unique())
  return unique

###"City"

In [ ]:
uniq_value("City")

sorted_unique("City")

There are 1526 different values in the City column

['Aberdeen',
 'Abilene',
 'Acton',
 'Addison',
 'Adel',
 'Advance',
 'Afton',
 'Agawam',
 'Aiken',
 'Aitkin',
 'Akron',
 'Alabaster',
 'Alachua',
 'Alamo',
 'Albany',
 'Albemarle',
 'Albertville',
 'Albuquerque',
 'Alexandria',
 'Aliquippa',
 'Allen',
 'Allentown',
 'Alliance',
 'Alpena',
 'Alpharetta',
 'Alsip',
 'Altamont',
 'Alton',
 'Amarillo',
 'Amelia',
 'American Fork',
 'Amery',
 'Amityville',
 'Amsterdam',
 'Anacortes',
 'Anaheim',
 'Anamosa',
 'Anderson',
 'Angola',
 'Ann Arbor',
 'Annandale',
 'Anniston',
 'Antigo',
 'Antwerp',
 'Apopka',
 'Appleton',
 'Appomattox',
 'Arcadia',
 'Arlington',
 'Artesia',
 'Asheboro',
 'Asheville',
 'Ashland',
 'Astoria',
 'Atascadero',
 'Athens',
 'Atlanta',
 'Atmore',
 'Aubrey',
 'Auburn',
 'Auburndale',
 'Augusta',
 'Aurora',
 'Austell',
 'Austin',
 'Avenel',
 'Bad Axe',
 'Baileyville',
 'Bakersfield',
 'Ball',
 'Ballston Spa',
 'Ballwin',
 'Bandera',
 'Barbourville',
 'Barnsdall',
 'Barnum',
 'Barnwell',
 'Batavia',
 'Batesville',
 'Baton Rouge',
 'Baxter',
 'Bay City',
 'Bay Minette',
 'Bay Shore',
 'Baytown',
 'Bealeton',
 'Bearsville',
 'Beatrice',
 'Beaumont',
 'Beaver Dam',
 'Beaverton',
 'Bedford',
 'Bedford Hills',
 'Beech Bluff',
 'Bel Air',
 'Belen',
 'Belford',
 'Bell Gardens',
 'Bellaire',
 'Belleville',
 'Bellevue',
 'Bellingham',
 'Bells',
 'Bellville',
 'Bellwood',
 'Belmar',
 'Belmont',
 'Beloit',
 'Belton',
 'Bend',
 'Benicia',
 'Bennettsville',
 'Bensalem',
 'Bensenville',
 'Benson',
 'Bentonville',
 'Berea',
 'Berkeley',
 'Bernardston',
 'Bessemer',
 'Bethlehem',
 'Bettendorf',
 'Beulaville',
 'Beverly Hills',
 'Billings',
 'Birmingham',
 'Bixby',
 'Blacklick',
 'Blair',
 'Blandinsville',
 'Bloomfield Hills',
 'Bloomington',
 'Blue Ridge',
 'Blue Springs',
 'Bluff City',
 'Bluffton',
 'Boca Raton',
 'Boiling Springs',
 'Boise',
 'Bolingbrook',
 'Boone',
 'Boonville',
 'Bordentown',
 'Boring',
 'Boston',
 'Boulder Creek',
 'Bountiful',
 'Bourbon',
 'Bow',
 'Bowdon',
 'Bowie',
 'Boyne City',
 'Boynton Beach',
 'Bradenton',
 'Bradford',
 'Braintree',
 'Brea',
 'Breckenridge',
 'Bremerton',
 'Bridgeport',
 'Bridgeton',
 'Bridport',
 'Brigham City',
 'Broadway',
 'Brockton',
 'Broken Arrow',
 'Bronx',
 'Brookfield',
 'Brookline',
 'Brooklyn',
 'Brookpark',
 'Broomall',
 'Broomfield',
 'Broussard',
 'Brownsburg',
 'Brownstown',
 'Brownsville',
 'Brunswick',
 'Buckhannon',
 'Buffalo',
 'Buford',
 'Burbank',
 'Burlingame',
 'Burlington',
 'Burnsville',
 'Burton',
 'Butte',
 'Buttonwillow',
 'Calabasas',
 'Caldwell',
 'Calumet City',
 'Calvin',
 'Cambridge',
 'Camden',
 'Campbell',
 'Candia',
 'Caneadea',
 'Canfield',
 'Cannon Falls',
 'Canoga Park',
 'Canton',
 'Canyon Country',
 'Cape Girardeau',
 'Carbondale',
 'Carencro',
 'Carey',
 'Carlinville',
 'Carlisle',
 'Carmel',
 'Carmichaels',
 'Carnation',
 'Carroll',
 'Carrollton',
 'Carson City',
 'Carthage',
 'Casey',
 'Casper',
 'Casselberry',
 'Cayce',
 'Cedar City',
 'Cedar Hill',
 'Centerville',
 'Central Point',
 'Centralia',
 'Century',
 'Cerritos',
 'Champaign',
 'Chandler',
 'Chantilly',
 'Chapman',
 'Chardon',
 'Charleston',
 'Charlotte',
 'Charlottesville',
 'Chatsworth',
 'Chattanooga',
 'Chelsea',
 'Cheney',
 'Chesapeake',
 'Chester',
 'Chestertown',
 'Cheswick',
 'Chicago',
 'Chicopee',
 'Childersburg',
 'China Grove',
 'Chino',
 'Choteau',
 'Chouteau',
 'Christiansburg',
 'Chula Vista',
 'Chunchula',
 'Cibolo',
 'Cincinnati',
 'Circleville',
 'Cisco',
 'City Of Industry',
 'Claremore',
 'Clark',
 'Clarksburg',
 'Clarksville',
 'Clay',
 'Clayton',
 'Clearfield',
 'Clearwater',
 'Cleburne',
 'Clemmons',
 'Cleveland',
 'Clinton',
 'Clinton Township',
 'Clio',
 'Clive',
 'Cloquet',
 'Clovis',
 'Cocoa Beach',
 'Cohocton',
 'Colbert',
 'Colchester',
 'Colcord',
 'College Place',
 'College Point',
 'Collinsville',
 'Colorado Springs',
 'Colton',
 'Columbia',
 'Columbiana',
 'Columbiaville',
 'Columbus',
 'Commerce City',
 'Comstock Park',
 'Concord',
 'Conley',
 'Conneautville',
 'Connellsville',
 'Conrad',
 'Conroe',
 'Converse',
 'Conway',
 'Cookeville',
 'Coopersburg',
 'Cornelius',
 'Corona',
 'Corona Del Mar',
 'Corpus Christi',
 'Cortlandt Manor',
 'Costa Mesa',
 'Cottage Grove',
 'Cottonwood',
 'Council Bluffs',
 'Coupeville',
 'Covington',
 'Coward',
 'Cowpens',
 'Cranfills Gap',
 'Cranford',
 'Cranston',
 'Crawfordsville',
 'Crescent',
 'Cresson',
 'Creston',
 'Cromwell',
 'Crookston',
 'Croswell',
 'Crown Point',
 'Crystal River',
 'Cudahy',
 'Cuero',
 'Cullman',
 'Culpeper',
 'Culver City',
 'Cumming',
 'Cypress',
 'Dade City',
 'Daingerfield',
 'Dale',
 'Dallas',
 'Dalton',
 'Damascus',
 'Dane',
 'Danville',
 'Darien',
 'Davenport',
 'Davidson',
 'Davis',
 'Dayton',
 'Daytona Beach',
 'De Witt',
 'Deatsville',
 'Decatur',
 'Deer Park',
 'Denison',
 'Denmark',
 'Denver',
 'Depew',
 'Derry',
 'Des Arc',
 'Des Moines',
 'Des Plaines',
 'Detroit',
 'Dexter',
 'Diamond',
 'Dickinson',
 'Dillon',
 'Dodge Center',
 'Dodge City',
 'Doral',
 'Dorchester',
 'Double Springs',
 'Dover',
 'Downey',
 'Draper',
 'Drayton',
 'Dresden',
 'Dry Fork',
 'Duarte',
 'Dublin',
 'Dunmore',
 'Durand',
 'Durango',
 'Durham',
 'Duryea',
 'Early',
 'East Alton',
 'East Claridon',
 'East Hartford',
 'East Liverpool',
 'East Longmeadow',
 'East Providence',
 'East Rochester',
 'East Syracuse',
 'East Windsor',
 'Eastman',
 'Eatonton',
 'Eau Claire',
 'Eden',
 'Eden Prairie',
 'Edgerton',
 'Edinburg',
 'Edmonds',
 'Edson',
 'Edwardsville',
 'Egg Harbor Township',
 'El Cajon',
 'El Paso',
 'Elbow Lake',
 'Elizabeth',
 'Elizabethton',
 'Elizabethtown',
 'Elk River',
 'Elkridge',
 'Ellenboro',
 'Ellerbe',
 'Elmhurst',
 'Elmira',
 'Elmwood Park',
 'Elyria',
 'Emeryville',
 'Eminence',
 'Encinitas',
 'Enfield',
 'Englewood',
 'Ennis',
 'Ephrata',
 'Erie',
 'Erlanger',
 'Escondido',
 'Espanola',
 'Essex Junction',
 'Etowah',
 'Eugene',
 'Everett',
 'Fair Lawn',
 'Fair Oaks',
 'Fairfield',
 'Fairmont',
 'Fairview Heights',
 'Fargo',
 'Farmingdale',
 'Farmington',
 'Farmington Hills',
 'Farmville',
 'Fayetteville',
 'Feasterville Trevose',
 'Federal Way',
 'Fenton',
 'Ferriday',
 'Finksburg',
 'Fitchburg',
 'Flint',
 'Floral City',
 'Florence',
 'Fond Du Lac',
 'Fontana',
 'Fordland',
 'Forest',
 'Forest City',
 'Forest Hill',
 'Forest Lake',
 'Forest Park',
 'Foristell',
 'Forrest',
 'Fort Jennings',
 'Fort Lauderdale',
 'Fort Loudon',
 'Fort Lupton',
 'Fort Mill',
 'Fort Myers',
 'Fort Smith',
 'Fort Wayne',
 'Fort Worth',
 'Fortuna',
 'Foster',
 'Fountain Hills',
 'Fountain Valley',
 'Frankfort',
 'Franklin',
 'Franklin Park',
 'Fraser',
 'Frederick',
 'Fredericksburg',
 'Freedom',
 'Freehold',
 'Freeport',
 'Fremont',
 'Fresno',
 'Frontenac',
 'Ft Wayne',
 'Fullerton',
 'Fuquay Varina',
 'Gadsden',
 'Gaffney',
 'Gainesville',
 'Gallatin',
 'Gallup',
 'Galva',
 'Garden City',
 'Garden Grove',
 'Gardena',
 'Gardendale',
 'Gardiner',
 'Gardner',
 'Garland',
 'Garner',
 'Garrison',
 'Gaston',
 'Gastonia',
 'Georgetown',
 'Georgiana',
 'Gettysburg',
 'Gilbert',
 'Gladstone',
 'Gladwin',
 'Glen Ellyn',
 'Glenbrook',
 'Glendale',
 'Glendive',
 'Glendora',
 'Glenville',
 'Gloucester City',
 'Goleta',
 'Gore',
 'Graham',
 'Grain Valley',
 'Granby',
 'Grand Island',
 'Grand Junction',
 'Grand Prairie',
 'Grand Rapids',
 'Grand Saline',
 'Grandville',
 'Grants Pass',
 'Grass Valley',
 'Gray Court',
 'Grayson',
 'Great Bend',
 'Great Meadows',
 'Greeley',
 'Green Bay',
 'Green Cove Springs',
 'Green Valley',
 'Greenacres',
 'Greenbrier',
 'Greene',
 'Greenfield',
 'Greensboro',
 'Greenville',
 'Greenwich',
 'Greer',
 'Gresham',
 'Gretna',
 'Groom',
 'Grove',
 'Grove City',
 'Guerneville',
 'Guthrie',
 'Hagerstown',
 'Hale',
 'Halethorpe',
 'Halifax',
 'Haltom City',
 'Hamburg',
 'Hamilton',
 'Hammond',
 'Hampstead',
 'Hampton',
 'Hancock',
 'Hanover',
 'Hanson',
 'Happy Valley',
 'Harbinger',
 'Harrisburg',
 'Harrison',
 'Harrisonburg',
 'Hart',
 'Hartford',
 'Haslet',
 'Hattiesburg',
 'Hauppauge',
 'Haverhill',
 'Havre De Grace',
 'Hawk Point',
 'Hayden',
 'Hayesville',
 'Hays',
 'Haysville',
 'Hayward',
 'Hazel Park',
 'Hazelwood',
 'Healdsburg',
 'Hearne',
 'Heber Springs',
 'Helena',
 'Hempstead',
 'Henderson',
 'Hendersonville',
 'Henrico',
 'Hercules',
 'Herkimer',
 'Hermosa Beach',
 'Hernando',
 'Hesperia',
 'Hialeah',
 'Hiawatha',
 'Hicksville',
 'High Point',
 'Highlandville',
 'Highmore',
 'Hill City',
 'Hilliard',
 'Hillsboro',
 'Hixson',
 'Holbrook',
 'Holden',
 'Holland',
 'Hollister',
 'Hollywood',
 'Holts Summit',
 'Hooksett',
 'Hope',
 'Hopewell',
 'Hopewell Junction',
 'Hopkins',
 'Hopkinsville',
 'Hopkinton',
 'Horseheads',
 'Houma',
 'Houston',
 'Howard Beach',
 'Howe',
 'Howell',
 'Huachuca City',
 'Hubbardston',
 'Hudson',
 'Hudson Falls',
 'Humble',
 'Huntersville',
 'Huntingburg',
 'Huntingdon',
 'Huntington',
 'Huntington Beach',
 'Huntington Station',
 'Huntsville',
 'Huron',
 'Hurricane',
 'Hutchinson',
 'Hyannis',
 'Hyattsville',
 'Hyde Park',
 'Idaho Falls',
 'Independence',
 'Indian Trail',
 'Indiana',
 'Indianapolis',
 'Inglewood',
 'Inglis',
 'Inkster',
 'Inver Grove Heights',
 'Inwood',
 'Iola',
 'Iowa City',
 'Irvine',
 'Irving',
 'Jackson',
 'Jacksonville',
 'Jamaica',
 'Jamaica Plain',
 'Jamestown',
 'Janesville',
 'Jasper',
 'Jefferson',
 'Jefferson City',
 'Jeffersonville',
 'Jensen Beach',
 'Jericho',
 'Johnson City',
 'Johnsonburg',
 'Johnstown',
 'Joliet',
 'Joplin',
 'Julian',
 'Junction City',
 'Jupiter',
 'Jurupa Valley',
 'Kalamazoo',
 'Kamas',
 'Kankakee',
 'Kannapolis',
 'Kansas City',
 'Kaukauna',
 'Keeseville',
 'Kenner',
 'Kennesaw',
 'Kennewick',
 'Kent',
 'Kernersville',
 'Key Largo',
 'Keysville',
 'Kilgore',
 'Kings Mountain',
 'Kingsport',
 'Kingston',
 'Kirksville',
 'Kirkville',
 'Kirkwood',
 'Knightstown',
 'Knoxville',
 'Kokomo',
 'La Center',
 'La Crosse',
 'La Grande',
 'La Habra',
 'La Jolla',
 'La Palma',
 'La Porte',
 'La Puente',
 'La Vergne',
 'La Verne',
 'Lafayette',
 'Lake City',
 'Lake Elsinore',
 'Lake Forest',
 'Lake Havasu City',
 'Lake Mary',
 'Lake Orion',
 'Lake Stevens',
 'Lake Wales',
 'Lake Zurich',
 'Lakeland',
 'Lakewood',
 'Lamar',
 'Lambertville',
 'Lamesa',
 'Lamont',
 'Lancaster',
 'Lansdale',
 'Lansing',
 'Lapeer',
 'Larchmont',
 'Laredo',
 'Largo',
 'Las Vegas',
 'Lathrop',
 'Laurel',
 'Laurens',
 'Lawndale',
 'Lawrence',
 'Lawrenceburg',
 'Lawrenceville',
 'Layton',
 'Leavenworth',
 'Leawood',
 'Lebanon',
 'Ledgewood',
 'Leeds',
 'Lees Summit',
 'Leesburg',
 'Leesville',
 'Leicester',
 'Lena',
 'Lenexa',
 'Lenoir City',
 'Leonardtown',
 'Levittown',
 'Lewisberry',
 'Lewiston',
 'Lewisville',
 'Lexington',
 'Libby',
 'Liberty',
 'Lilburn',
 'Lillington',
 'Lincoln',
 'Linden',
 'Lindenhurst',
 'Lisle',
 'Little Rock',
 'Littleton',
 'Live Oak',
 'Livermore',
 'Livingston',
 'Livonia',
 'Lockeford',
 'Lockport',
 'Lombard',
 'London',
 'Lone Tree',
 'Long Beach',
 'Long Lake',
 'Long Prairie',
 'Longmont',
 'Longview',
 'Longwood',
 'Loomis',
 'Loretto',
 'Lorton',
 'Los Angeles',
 'Lott',
 'Louisville',
 'Loveland',
 'Lovettsville',
 'Lovington',
 'Lowell',
 'Loysburg',
 'Lubbock',
 'Lucedale',
 'Lugoff',
 'Lyman',
 'Lynbrook',
 'Lynchburg',
 'Lynnwood',
 'Lynwood',
 'Lyons',
 'Macclenny',
 'Machesney Park',
 'Machias',
 'Macon',
 'Macungie',
 'Madera',
 'Madison',
 'Madison Heights',
 'Maitland',
 'Malcom',
 'Malvern',
 'Mamaroneck',
 'Manassas',
 'Manchester',
 'Mankato',
 'Mansfield',
 'Manteno',
 'Maple Shade',
 'Mapleton',
 'Margate',
 'Marianna',
 'Marietta',
 'Marion',
 'Mariposa',
 'Marlborough',
 'Marlow',
 'Marshall',
 'Mart',
 'Marysville',
 'Masonville',
 'Massillon',
 'Matthews',
 'Mays Landing',
 'Maysville',
 'Maywood',
 'Mcallen',
 'Meadowview',
 'Mears',
 'Mechanicsburg',
 'Mechanicsville',
 'Medford',
 'Medina',
 'Medley',
 'Melbourne',
 'Melrose',
 'Melrose Park',
 'Memphis',
 'Menominee',
 'Menomonee Falls',
 'Mentor',
 'Meridianville',
 'Merrifield',
 'Mesa',
 'Mexico',
 'Miami',
 'Middletown',
 'Midland',
 'Milaca',
 'Milan',
 'Milford',
 'Millbury',
 'Milledgeville',
 'Millstadt',
 'Milpitas',
 'Milton',
 'Milwaukee',
 'Minneapolis',
 'Minocqua',
 'Mira Loma',
 'Mission',
 'Mission Viejo',
 'Missouri City',
 'Mobile',
 'Mokena',
 'Moline',
 'Monroe',
 'Monroeville',
 'Montclair',
 'Monterey',
 'Montgomery',
 'Montgomery City',
 'Monticello',
 'Mooresville',
 'Moorhead',
 'Moravia',
 'Morgantown',
 'Morris',
 'Morrisville',
 'Morro Bay',
 'Morton Grove',
 'Moscow Mills',
 'Mounds',
 'Mount Hope',
 'Mount Juliet',
 'Mount Olive',
 'Mount Upton',
 'Mount Vernon',
 'Mount Washington',
 'Mountain City',
 'Mountain View',
 'Mt Pleasant',
 'Mukwonago',
 'Muncie',
 'Mundelein',
 'Munroe Falls',
 'Murfreesboro',
 'Murrieta',
 'Murrysville',
 'Muscatine',
 'Muscoda',
 'Muskegon',
 'Muskogee',
 'Myerstown',
 'Nacogdoches',
 'Napa',
 'Naperville',
 'Nashua',
 'Nashville',
 'Neeses',
 'Neosho',
 'Neshanic Station',
 'Nevada',
 'New Albany',
 'New Bedford',
 'New Braunfels',
 'New Britain',
 'New Caney',
 'New Era',
 'New Holstein',
 'New Hope',
 'New Iberia',
 'New Kensington',
 'New Milford',
 'New Philadelphia',
 'New Rochelle',
 'New Springfield',
 'New Stanton',
 'New York',
 'Newark',
 'Newburgh',
 'Newbury Park',
 'Newfield',
 'Newington',
 'Newman Grove',
 'Newport',
 'Newport News',
 'Newton',
 'Niagara Falls',
 'Nicholasville',
 'Niles',
 'Nixa',
 'Norco',
 'Norfolk',
 'Normal',
 'Norman',
 'North Canton',
 'North Dartmouth',
 'North Fort Myers',
 'North Haven',
 'North Highlands',
 'North Hollywood',
 'North Las Vegas',
 'North Liberty',
 'North Little Rock',
 'North Miami',
 'North Miami Beach',
 'North Platte',
 'North Port',
 'North Richland Hills',
 'North Weymouth',
 'Northport',
 'Northridge',
 'Northumberland',
 'Norwalk',
 'Nottingham',
 'Novi',
 'O Fallon',
 'Oak Grove',
 'Oak Ridge',
 'Oakes',
 'Oakland',
 'Oakland Park',
 'Oakley',
 'Oakwood',
 'Ocala',
 'Oceanside',
 'Ocoee',
 'Oconomowoc',
 ...]

###"State"

In [ ]:
uniq_value("State")

sorted_unique("State")

There are 48 different values in the State column

['AL',
 'AR',
 'AZ',
 'CA',
 'CO',
 'CT',
 'DE',
 'FL',
 'GA',
 'IA',
 'ID',
 'IL',
 'IN',
 'KS',
 'KY',
 'LA',
 'MA',
 'MD',
 'ME',
 'MI',
 'MN',
 'MO',
 'MS',
 'MT',
 'NC',
 'ND',
 'NE',
 'NH',
 'NJ',
 'NM',
 'NV',
 'NY',
 'OH',
 'OK',
 'OR',
 'PA',
 'RI',
 'SC',
 'SD',
 'TN',
 'TX',
 'UT',
 'VA',
 'VT',
 'WA',
 'WI',
 'WV',
 'WY']

###"County"

In [ ]:
uniq_value("County")

sorted_unique("County")

There are 697 different values in the County column

['Ada',
 'Adair',
 'Adams',
 'Addison',
 'Aiken',
 'Aitkin',
 'Alachua',
 'Alamance',
 'Alameda',
 'Albany',
 'Alexandria City',
 'Allegan',
 'Allegany',
 'Allegheny',
 'Allen',
 'Alpena',
 'Amherst',
 'Anderson',
 'Androscoggin',
 'Anne Arundel',
 'Anoka',
 'Appanoose',
 'Appomattox',
 'Arapahoe',
 'Atlantic',
 'Auglaize',
 'Autauga',
 'Baker',
 'Baldwin',
 'Baltimore',
 'Bandera',
 'Banks',
 'Barbour',
 'Barnes',
 'Barnstable',
 'Barnwell',
 'Bartholomew',
 'Barton',
 'Bay',
 'Beaufort',
 'Beaver',
 'Bedford',
 'Belknap',
 'Bell',
 'Belmont',
 'Benton',
 'Bergen',
 'Berks',
 'Bernalillo',
 'Bexar',
 'Bibb',
 'Bingham',
 'Blair',
 'Blount',
 'Blue Earth',
 'Bonneville',
 'Boone',
 'Bosque',
 'Boulder',
 'Bowie',
 'Box Elder',
 'Bradford',
 'Bradley',
 'Brazoria',
 'Brevard',
 'Bristol',
 'Bronx',
 'Broomfield',
 'Broward',
 'Brown',
 'Bryan',
 'Bucks',
 'Bullitt',
 'Bulloch',
 'Buncombe',
 'Burlington',
 'Butler',
 'Butte',
 'Cabarrus',
 'Caldwell',
 'Calhoun',
 'Callaway',
 'Calumet',
 'Cambria',
 'Camden',
 'Cameron',
 'Canadian',
 'Canyon',
 'Cape Girardeau',
 'Carlton',
 'Carroll',
 'Carson',
 'Carson City',
 'Carter',
 'Cass',
 'Catawba',
 'Cayuga',
 'Cedar',
 'Centre',
 'Champaign',
 'Charles',
 'Charlevoix',
 'Charlotte',
 'Charlottesville City',
 'Chatham',
 'Chautauqua',
 'Chemung',
 'Chenango',
 'Cherokee',
 'Chesapeake City',
 'Chester',
 'Chesterfield',
 'Chittenden',
 'Christian',
 'Citrus',
 'Clackamas',
 'Clare',
 'Clark',
 'Clarke',
 'Clatsop',
 'Clay',
 'Clayton',
 'Clearfield',
 'Cleburne',
 'Clermont',
 'Cleveland',
 'Clinton',
 'Cobb',
 'Cochise',
 'Codington',
 'Colbert',
 'Cole',
 'Collin',
 'Columbia',
 'Columbiana',
 'Comal',
 'Concordia',
 'Contra Costa',
 'Cook',
 'Covington',
 'Crawford',
 'Crockett',
 'Cross',
 'Cullman',
 'Culpeper',
 'Cumberland',
 'Currituck',
 'Cuyahoga',
 'Dakota',
 'Dallas',
 'Dane',
 'Dauphin',
 'Davidson',
 'Daviess',
 'Davis',
 'Dawson',
 'De Witt',
 'Dekalb',
 'Delaware',
 'Denton',
 'Denver',
 'Deschutes',
 'Desoto',
 'Dickey',
 'Dickinson',
 'Dillon',
 'Dodge',
 'Dorchester',
 'Douglas',
 'Drew',
 'Dubois',
 'Dupage',
 'Duplin',
 'Durham',
 'Dutchess',
 'Duval',
 'East Baton Rouge',
 'Eastland',
 'Eau Claire',
 'Ector',
 'Eddy',
 'El Dorado',
 'El Paso',
 'Elk',
 'Ellis',
 'Erie',
 'Escambia',
 'Essex',
 'Etowah',
 'Fairfax',
 'Fairfield',
 'Falls',
 'Faulkner',
 'Fauquier',
 'Fayette',
 'Florence',
 'Floyd',
 'Fond Du Lac',
 'Ford',
 'Forrest',
 'Forsyth',
 'Fort Bend',
 'Fountain',
 'Franklin',
 'Frederick',
 'Freeborn',
 'Fresno',
 'Fulton',
 'Gage',
 'Galveston',
 'Garvin',
 'Gaston',
 'Geary',
 'Geauga',
 'Genesee',
 'George',
 'Georgetown',
 'Gilmer',
 'Gladwin',
 'Glenn',
 'Gloucester',
 'Goodhue',
 'Grafton',
 'Graham',
 'Grand Traverse',
 'Grant',
 'Grayson',
 'Green Lake',
 'Greene',
 'Greenville',
 'Gregg',
 'Grundy',
 'Guadalupe',
 'Guilford',
 'Gwinnett',
 'Halifax',
 'Hall',
 'Hamilton',
 'Hampden',
 'Hampshire',
 'Hancock',
 'Hanover',
 'Hardin',
 'Harford',
 'Harnett',
 'Harris',
 'Harrisonburg City',
 'Hartford',
 'Harvey',
 'Henderson',
 'Hendricks',
 'Hennepin',
 'Henrico',
 'Henry',
 'Herkimer',
 'Hernando',
 'Hidalgo',
 'Highland',
 'Hill',
 'Hillsborough',
 'Hinds',
 'Hood',
 'Hopkins',
 'Horry',
 'Howard',
 'Howell',
 'Humboldt',
 'Huntingdon',
 'Huntington',
 'Huron',
 'Hyde',
 'Iberia',
 'Independence',
 'Indian River',
 'Indiana',
 'Ingham',
 'Ionia',
 'Iosco',
 'Iredell',
 'Iron',
 'Island',
 'Jackson',
 'Jasper',
 'Jefferson',
 'Jessamine',
 'Johnson',
 'Johnston',
 'Jones',
 'Josephine',
 'Kalamazoo',
 'Kalkaska',
 'Kanawha',
 'Kandiyohi',
 'Kane',
 'Kankakee',
 'Kaufman',
 'Kennebec',
 'Kent',
 'Kenton',
 'Kern',
 'Kershaw',
 'King',
 'Kings',
 'Kitsap',
 'Klickitat',
 'Knox',
 'Kootenai',
 'La Crosse',
 'La Plata',
 'La Porte',
 'Lac Qui Parle',
 'Lackawanna',
 'Laclede',
 'Lafayette',
 'Lagrange',
 'Lake',
 'Lancaster',
 'Lane',
 'Langlade',
 'Lapeer',
 'Larimer',
 'Lauderdale',
 'Laurel',
 'Laurens',
 'Lawrence',
 'Lea',
 'Leavenworth',
 'Lebanon',
 'Lee',
 'Lehigh',
 'Lenawee',
 'Leon',
 'Levy',
 'Lewis',
 'Lewis And Clark',
 'Lexington',
 'Liberty',
 'Licking',
 'Limestone',
 'Lincoln',
 'Linn',
 'Litchfield',
 'Livingston',
 'Logan',
 'Lorain',
 'Los Angeles',
 'Loudon',
 'Loudoun',
 'Love',
 'Lowndes',
 'Lubbock',
 'Lucas',
 'Luzerne',
 'Lynchburg City',
 'Lyon',
 'Macomb',
 'Macon',
 'Macoupin',
 'Madera',
 'Madison',
 'Mahoning',
 'Malheur',
 'Manassas City',
 'Manassas Park City',
 'Manatee',
 'Manitowoc',
 'Maricopa',
 'Marin',
 'Marion',
 'Mariposa',
 'Marlboro',
 'Marshall',
 'Martin',
 'Mayes',
 'Mccracken',
 'Mcdonough',
 'Mcdowell',
 'Mchenry',
 'Mckinley',
 'Mclean',
 'Mclennan',
 'Mcminn',
 'Mcnairy',
 'Meade',
 'Mecklenburg',
 'Medina',
 'Menominee',
 'Mercer',
 'Merrimack',
 'Mesa',
 'Miami-dade',
 'Middlesex',
 'Midland',
 'Mille Lacs',
 'Milwaukee',
 'Minnehaha',
 'Mississippi',
 'Mobile',
 'Mohave',
 'Monmouth',
 'Monongalia',
 'Monroe',
 'Monterey',
 'Montgomery',
 'Morgan',
 'Morris',
 'Mower',
 'Multnomah',
 'Muscatine',
 'Muskegon',
 'Muskingum',
 'Muskogee',
 'Nacogdoches',
 'Napa',
 'Nash',
 'Nassau',
 'Natrona',
 'Nevada',
 'New Castle',
 'New Hanover',
 'New Haven',
 'New London',
 'New York',
 'Newport News City',
 'Newton',
 'Niagara',
 'Nicollet',
 'Noble',
 'Nobles',
 'Nolan',
 'Norfolk',
 'Norfolk City',
 'Northumberland',
 'Nueces',
 'Oakland',
 'Obion',
 'Ocean',
 'Oceana',
 'Oconto',
 'Ohio',
 'Oklahoma',
 'Oldham',
 'Olmsted',
 'Oneida',
 'Onondaga',
 'Onslow',
 'Ontario',
 'Orange',
 'Orangeburg',
 'Orleans',
 'Osage',
 'Oswego',
 'Ottawa',
 'Outagamie',
 'Ozark',
 'Palm Beach',
 'Passaic',
 'Patrick',
 'Paulding',
 'Payne',
 'Pearl River',
 'Pembina',
 'Pennington',
 'Penobscot',
 'Peoria',
 'Pettis',
 'Phelps',
 'Philadelphia',
 'Pickaway',
 'Pickens',
 'Pierce',
 'Pike',
 'Pima',
 'Pinellas',
 'Pitt',
 'Pittsylvania',
 'Placer',
 'Pleasants',
 'Plymouth',
 'Poinsett',
 'Polk',
 'Pondera',
 'Pope',
 'Portage',
 'Porter',
 'Portsmouth City',
 'Pottawatomie',
 'Pottawattamie',
 'Potter',
 'Poweshiek',
 'Prairie',
 'Pratt',
 'Prince Edward',
 'Prince Georges',
 'Prince William',
 'Providence',
 'Prowers',
 'Pueblo',
 'Pulaski',
 'Putnam',
 'Queen Annes',
 'Queens',
 'Racine',
 'Ramsey',
 'Randall',
 'Randolph',
 'Rapides',
 'Redwood',
 'Reno',
 'Rensselaer',
 'Republic',
 'Richland',
 'Richmond',
 'Richmond City',
 'Rio Arriba',
 'Ritchie',
 'Riverside',
 'Robertson',
 'Rock',
 'Rock Island',
 'Rockingham',
 'Rockwall',
 'Rogers',
 'Rooks',
 'Ross',
 'Rowan',
 'Rusk',
 'Russell',
 'Rutherford',
 'Sacramento',
 'Saginaw',
 'Saint Charles',
 'Saint Clair',
 'Saint Francois',
 'Saint Johns',
 'Saint Landry',
 'Saint Lawrence',
 'Saint Louis',
 'Saint Louis City',
 'Saint Martin',
 'Saint Marys',
 'Salem',
 'Salt Lake',
 'San Bernardino',
 'San Diego',
 'San Francisco',
 'San Joaquin',
 'San Juan',
 'San Luis Obispo',
 'San Mateo',
 'Sandusky',
 'Sangamon',
 'Sanilac',
 'Santa Barbara',
 'Santa Clara',
 'Santa Cruz',
 'Santa Rosa',
 'Sarasota',
 'Saratoga',
 'Sarpy',
 'Schuylkill',
 'Scioto',
 'Scott',
 'Scotts Bluff',
 'Sebastian',
 'Sedgwick',
 'Seminole',
 'Seneca',
 'Sequoyah',
 'Shasta',
 'Shawano',
 'Shawnee',
 'Sheboygan',
 'Shelby',
 'Sherburne',
 'Sherman',
 'Silver Bow',
 'Skagit',
 'Smith',
 'Snohomish',
 'Solano',
 'Somerset',
 'Sonoma',
 'Spartanburg',
 'Spencer',
 'Spokane',
 'Spotsylvania',
 'St Joseph',
 'Stafford',
 'Stanly',
 'Stanton',
 'Stark',
 'Stearns',
 'Stephens',
 'Stephenson',
 'Steuben',
 'Stewart',
 'Stoddard',
 'Story',
 'Strafford',
 'Suffolk',
 'Sullivan',
 'Summit',
 'Sumner',
 'Sumter',
 'Surry',
 'Sussex',
 'Suwannee',
 'Talladega',
 'Taney',
 'Taos',
 'Tarrant',
 'Taylor',
 'Terrebonne',
 'Teton',
 'Texas',
 'Tift',
 'Tillman',
 'Tioga',
 'Tippecanoe',
 'Tipton',
 'Todd',
 'Tolland',
 'Toole',
 'Travis',
 'Trempealeau',
 'Trumbull',
 'Tulsa',
 'Turner',
 'Tuscaloosa',
 'Tuscarawas',
 'Tuscola',
 'Twin Falls',
 'Tyrrell',
 'Ulster',
 'Union',
 'Upshur',
 'Utah',
 'Uvalde',
 'Valencia',
 'Van Zandt',
 'Vance',
 'Venango',
 'Ventura',
 'Vermilion',
 'Vernon',
 'Victoria',
 'Vigo',
 'Vilas',
 'Virginia Beach City',
 'Volusia',
 'Wabash',
 'Wake',
 'Walker',
 'Walla Walla',
 'Walworth',
 'Warren',
 'Warrick',
 'Washington',
 'Washoe',
 'Washtenaw',
 'Waukesha',
 'Waushara',
 'Wayne',
 'Waynesboro City',
 'Webb',
 'Webster',
 'Weld',
 'Wells',
 'Westchester',
 'Westmoreland',
 'Whatcom',
 'White',
 'Whitfield',
 'Wichita',
 'Wicomico',
 'Wilkes',
 'Will',
 'Williams',
 'Williamson',
 'Wilson',
 'Windham',
 'Winnebago',
 'Winona',
 'Winston',
 'Wise',
 'Woodbury',
 'Worcester',
 'Wright',
 'Wyandot',
 'Wyandotte',
 'Yadkin',
 'Yakima',
 'Yavapai',
 'Yellowstone',
 'Yolo',
 'York']

###"Employee Range"

In [ ]:
uniq_value("Employee Range")

sorted_unique("Employee Range")

There are 8 different values in the Employee Range column

['1 To 4',
 '10 To 19',
 '100 To 249',
 '1000 To 49',
 '20 To 49',
 '250 To 499',
 '5 To 9',
 '50 To 99']

###"Annual Sales"

In [ ]:
uniq_value("Annual Sales")

sorted_unique("Annual Sales")

There are 11 different values in the Annual Sales column

['$1 To 2.5 Million',
 '$10 To 20 Million',
 '$100 To 500 Million',
 '$2.5 To 5 Million',
 '$20 To 50 Million',
 '$5 To 10 Million',
 '$50 To 100 Million',
 '$500,000 To $1 Million',
 '$500,000 To 1 Millio',
 'Less Than $500,000',
 'Unknown']

###"SIC Code"

In [ ]:
uniq_value("SIC Code")

sorted_unique("SIC Code")

There are 6 different values in the SIC Code column

[552100, 552101, 552102, 552103, 552198, 552199]

###"Industry"

In [ ]:
uniq_value("Industry")

sorted_unique("Industry")

col_dist("Industry")

There are 11 different values in the Industry column

Industry
Truck-dealers-used                             2959
Automobile Racing Cars                         2051
Automobile-antique & Classic                   1480
Used Car Dealers                                832
Ret Used Automobiles                            467
Used Car Dealers, Nec                           344
Motor Vehicle Dealers-used Only                 180
Automobile Dealers Performance & Race            46
Used Car Dealers; Nec                            35
Automobiles, Used Cars Only                      14
Motor Vehicle Dealers (used Only)                 2
Trucks, Tractors, And Trailers: Used              1
Used Car Dealers, Nec,5521-9902,automobiles       1
Name: count, dtype: int64

"**Nec**", or Not Elsewhere Classified, is a term used in various industry classification systems to categorize data that does not fit into any of the existing categories within the system.

"**Ret**", an abbreviation for retail

##Find out wrong data format

###"Zip"

In [ ]:
uniq_value("Zip")

sorted_unique("Zip")

There are 2683 different values in the Zip column

['01001-2015',
 '01028-7000',
 '01033-9506',
 '01082-1583',
 '01104-3016',
 '01337-9586',
 '01420-5935',
 '01440-3101',
 '01452-1651',
 '01463-1564',
 '01468-1539',
 '01475-1153',
 '01527-1915',
 '01568-1312',
 '01569-1177',
 '01569-2001',
 '01583-1817',
 '01603-1926',
 '01610-1423',
 '01720-5684',
 '01748-1160',
 '01752-1981',
 '01778-4907',
 '01832-3735',
 '01835-8500',
 '01841-3528',
 '01852-2531',
 '01876-1768',
 '01952-1238',
 '01952-1830',
 '01960-3806',
 '02109-4028',
 '02119-3647',
 '02130-2664',
 '02136-2959',
 '02151-1429',
 '02155-4641',
 '02184-2407',
 '02301-2407',
 '02339-2425',
 '02341-1504',
 '02364-2288',
 '02368-1827',
 '02370-1732',
 '02382-1863',
 '02493-1567',
 '02601-1815',
 '02601-5607',
 '02744-2535',
 '02747-3320',
 '02747-3617',
 '02767-1966',
 '02771-2032',
 '02780-2167',
 '02790-2819',
 '02825-1309',
 '02876-0893',
 '02879-1314',
 '02893-4113',
 '02908-4427',
 '02910-3729',
 '02914-3594',
 '03034-2111',
 '03038-4519',
 '03051-3907',
 '03063-1706',
 '03106-1853',
 '03782-2802',
 '03836-5026',
 '03841-2337',
 '03841-2800',
 '03842-3350',
 '03848-3529',
 '03858-3107',
 '03874-4299',
 '03878-1588',
 '03894-4416',
 '04032-7013',
 '04210-3806',
 '04345-5975',
 '04353-3147',
 '04654-1405',
 '04930-1304',
 '04976-1404',
 '04989-3110',
 '05446-5813',
 '05452-3168',
 '05468-3232',
 '05734-9678',
 '06019-2525',
 '06051-3342',
 '06076-1327',
 '06082-3212',
 '06088-9687',
 '06089-9775',
 '06096-1137',
 '06096-1571',
 '06108-4206',
 '06110-2238',
 '06111-1208',
 '06114-2105',
 '06277-0278',
 '06371-1763',
 '06473-1623',
 '06473-3926',
 '06478-1176',
 '06484-1423',
 '06484-4646',
 '06488-1573',
 '06492-3630',
 '06492-6205',
 '06607-1111',
 '06610-3238',
 '06614-4753',
 '06776-3413',
 '06830-5204',
 '06890-0668',
 '06903-4318',
 '07001-1320',
 '07016-2627',
 '07036-3201',
 '07054-2345',
 '07057-0049',
 '07066-1752',
 '07104-3815',
 '07105-3731',
 '07105-3760',
 '07407-1540',
 '07410-3121',
 '07462-3206',
 '07514-2027',
 '07718-1633',
 '07719-2319',
 '07727-1605',
 '07728-2369',
 '07801-4210',
 '07838-2042',
 '07852-9708',
 '07866-3833',
 '07934-2059',
 '08043-2972',
 '08052-1725',
 '08075-1235',
 '08075-1869',
 '08084-1521',
 '08234-5215',
 '08330-4907',
 '08343-1703',
 '08344-5108',
 '08360-1914',
 '08360-4568',
 '08505-1516',
 '08505-2111',
 '08525-1831',
 '08527-3064',
 '08701-4516',
 '08755-1209',
 '08853-4304',
 '08872-2744',
 '10006-1421',
 '10017-5550',
 '10019-3584',
 '10023-4163',
 '1020',
 '10306-3426',
 '10314-6781',
 '10463-5144',
 '10472',
 '10474-6811',
 '10475-1322',
 '10507-2024',
 '10538',
 '10543-1835',
 '10562-4139',
 '10562-5973',
 '10567-7344',
 '10805-2011',
 '11096',
 '11203-6532',
 '11204',
 '11207-1700',
 '11207-1801',
 '11207-2812',
 '11219',
 '11228-1111',
 '11231-1605',
 '11233-4813',
 '11356-2633',
 '11373-3750',
 '11414-3501',
 '11429-1230',
 '11435-5830',
 '11550',
 '11563-3741',
 '11701-1102',
 '11704-1315',
 '11706-1219',
 '11706-1229',
 '11729-3709',
 '11729-7236',
 '11741',
 '11746-3147',
 '11753-1007',
 '11757-3621',
 '11772-4507',
 '11779-6856',
 '11788-2950',
 '11796-1831',
 '11801-5030',
 '11801-6521',
 '11968-5251',
 '12009-5204',
 '12010-6509',
 '12020-3633',
 '12020-3664',
 '12182-2529',
 '12205-3533',
 '12401-2609',
 '12409-0135',
 '12533-5369',
 '12533-5806',
 '12550-8316',
 '12564',
 '12590-6435',
 '12601',
 '12839-1275',
 '12944',
 '12992-3600',
 '13021-9105',
 '13041-9673',
 '13041-9689',
 '13057-1092',
 '13082-9467',
 '13114-3405',
 '13167-3247',
 '13204-2305',
 '13206-2988',
 '13208-2805',
 '13209-2317',
 '13316-4933',
 '13350-1022',
 '13440-6117',
 '13478-3105',
 '13667-0614',
 '13809',
 '13827-3204',
 '14043-3227',
 '14075-2105',
 '14075-3933',
 '14103-9635',
 '14150',
 '14150-2333',
 '14203-3028',
 '14211-1041',
 '14221-6031',
 '14224-4655',
 '14301-2331',
 '14445-1336',
 '14505-9732',
 '14519-9759',
 '14526-1944',
 '14564',
 '14564-8931',
 '14580-9188',
 '14589-0028',
 '14605-2741',
 '14606-4316',
 '14611-1906',
 '14622',
 '14624-4646',
 '14701-9701',
 '14717-8610',
 '14784',
 '14801-1145',
 '14826-9714',
 '14845-3200',
 '14870-8922',
 '15001-1015',
 '15024-2202',
 '15037-3114',
 '15068-1434',
 '15083-1140',
 '15146-2016',
 '15205-1814',
 '15225',
 '15237-2605',
 '15320',
 '15425-0674',
 '15501-1144',
 '15666-2800',
 '15668-1400',
 '15672-2700',
 '15672-9415',
 '15701-3585',
 '15701-5002',
 '15845',
 '15906',
 '15963-9108',
 '16052-2107',
 '16116-1315',
 '16145-4526',
 '16364-3115',
 '16406-5657',
 '16510-1862',
 '16510-2386',
 '16617-1520',
 '16622',
 '16652',
 '16659-9516',
 '16673-2258',
 '16830-0247',
 '16830-3517',
 '16844-8465',
 '17013-1588',
 '17013-1617',
 '17042-2522',
 '17042-9609',
 '17050-2801',
 '17050-5235',
 '17055-4507',
 '17057-2998',
 '17067-1826',
 '17224-9794',
 '17235',
 '17325-8356',
 '17339-9212',
 '17339-9517',
 '17339-9714',
 '17370-9006',
 '17370-9218',
 '17522-4201',
 '17536-9633',
 '17857-1203',
 '17961-1004',
 '18015-4130',
 '18036-1653',
 '18062-1727',
 '18087',
 '18104-1971',
 '18109-9611',
 '18360-1072',
 '18512-4522',
 '18642-1034',
 '18702-5566',
 '18704-3826',
 '18938-1392',
 '18964-2713',
 '18977-1024',
 '19008-2519',
 '19013-2665',
 '19020-1578',
 '19020-4556',
 '19053',
 '19054-1002',
 '19067-7229',
 '19124-5113',
 '19124-5603',
 '19135-2539',
 '19135-4309',
 '19153',
 '19355-2419',
 '19365-1128',
 '19380-2177',
 '19446-2109',
 '19465-8718',
 '19551-8902',
 '19601-1714',
 '19601-3042',
 '19702-1301',
 '19802-4601',
 '19804-1223',
 '19807-2550',
 '19808-5107',
 '19938-2348',
 '19947-4445',
 '19956-1127',
 '19971',
 '20109-4500',
 '20110-4176',
 '20111-1743',
 '20111-2229',
 '20111-2400',
 '20151',
 '20166-9504',
 '20175-3709',
 '20180-2900',
 '20187-2328',
 '20601-3143',
 '20650-6029',
 '20721-2301',
 '20723',
 '20746-3124',
 '20782',
 '20850-1313',
 '20853-1830',
 '20871-4312',
 '20904-1816',
 '21014-0186',
 '21048-2306',
 '21075-5629',
 '21076-1526',
 '21076-1766',
 '21078-2129',
 '21122-2017',
 '21227-4134',
 '21234-2011',
 '21236-3817',
 '21236-5725',
 '21286-5911',
 '21613-3502',
 '21619-2601',
 '21620-1003',
 '21657-1508',
 '21701-5651',
 '21740-2129',
 '21787-2729',
 '21797-7838',
 '21801-2139',
 '21801-3328',
 '2191',
 '22079',
 '22116-3854',
 '22150-3808',
 '22180-4309',
 '22304-4806',
 '22314-2931',
 '22408-2630',
 '22553-1948',
 '22554-3714',
 '22701',
 '22712-7121',
 '22801-1636',
 '22815',
 '22815-3608',
 '22902-5951',
 '22968-3034',
 '22980-4811',
 '23111-3696',
 '23116-2443',
 '23150-1447',
 '23224-7801',
 '23228-2505',
 '23235',
 '23320-2635',
 '23454-4554',
 '23454-4759',
 '23455-3006',
 '23462',
 '23462-5306',
 '23502',
 '23510-1637',
 '23606-1903',
 '23701-2801',
 '23707-3125',
 '23901-5479',
 '23947',
 '24073-7905',
 '24153-5029',
 '24171-4000',
 '24361-3011',
 '24380-4847',
 '24502-2446',
 '24504-4529',
 '24520-3617',
 '24520-3655',
 '24522-0339',
 '24540-5245',
 '24541-0913',
 '24549-4940',
 '24551-1014',
 '24558-3215',
 '24572',
 '24586-2801',
 '24701',
 '25130',
 '25302-4907',
 '25303-1539',
 '25526-2604',
 '26003-4005',
 '26184-7004',
 '26201-2719',
 '26346',
 '26505-3020',
 '26508-2354',
 '26554',
 '26554-8916',
 '27012-8619',
 '27012-9014',
 '27045-9761',
 '27047-9145',
 '27055-5722',
 '27107-1310',
 '27205-0118',
 '27215',
 '27217-1174',
 '27217-8740',
 '27253-9233',
 '27260-8190',
 '27263-1662',
 '27263-2344',
 '27265-1937',
 '27265-9255',
 '27284-3693',
 '27288-3267',
 '27312-9717',
 '27317-7285',
 '27350-9246',
 '27360-2753',
 '27360-5560',
 '27360-7419',
 '27360-8927',
 '27361-0915',
 '27370-7646',
 '27374',
 '27409-9704',
 '27409-9711',
 '27410-6121',
 '27419-8928',
 '27455-1480',
 '27504-1855',
 '27526-2616',
 '27529-2533',
 '27536-4510',
 '27546-1703',
 '27560-9317',
 '27587-2930',
 '27596-9302',
 '27604-3383',
 '27615-5601',
 '27703-4756',
 '27804-2811',
 '27830-9249',
 '27834-0751',
 '27839-8820',
 '27870-4328',
 '27889-7690',
 '27925-9769',
 '27941-9765',
 '28001-3733',
 '28012-2899',
 '28017-0385',
 '28023-8644',
 '28025-2615',
 '28025-9234',
 '28027',
 '28027-3708',
 '28027-6194',
 '28027-7192',
 '28027-7571',
 '28027-8962',
 '28031-6123',
 '28036-9029',
 '28037-0355',
 '28037-7226',
 '28040-7641',
 '28043-3792',
 '28054-8450',
 '28075',
 '28075-7480',
 '28078-5936',
 '28078-6417',
 '28078-8906',
 '28079-7677',
 '28083-7400',
 '28086-7742',
 '28086-9245',
 '28086-9488',
 '28105-1539',
 '28110-8455',
 '28112-6729',
 '28115-4210',
 '28115-6777',
 '28115-8022',
 '28115-8258',
 '28115-9590',
 '28115-9591',
 '28115-9594',
 '28117-4376',
 '28117-6706',
 '28117-6846',
 '28117-6847',
 '28117-8006',
 '28117-8063',
 '28150-9573',
 '28152-6992',
 '28206',
 '28212',
 '28214',
 '28217-2708',
 '28217-4350',
 '28217-4466',
 '28262-5703',
 '28269-2500',
 '28269-4400',
 '28269-4802',
 '28277-4556',
 '28304-2413',
 '28304-3043',
 '28338-9140',
 '28379-7929',
 '28412-2611',
 '28518-6612',
 '28574-7268',
 '28580-2067',
 '28635-9347',
 '28673-7717',
 '28673-7723',
 '28677-6235',
 '28689-0027',
 '28697-8367',
 '28697-8640',
 '28748-9487',
 '28752-3523',
 '28781-7400',
 '28791-3411',
 '28792-5794',
 '28792-5824',
 '28806-1050',
 '2889',
 '28904-6149',
 '29033-3325',
 '29053-9744',
 '29070-7865',
 '29072-2203',
 '29072-2504',
 '29072-8623',
 '29078-9414',
 '29107-9331',
 '29169-5603',
 '29169-6418',
 '29223-4563',
 '29229-9061',
 '29303-1738',
 '29303-4718',
 '29330-9504',
 '29341-5617',
 '29360-3602',
 '29365',
 '29365-1625',
 '29440-9259',
 '29485-8719',
 '29502-4509',
 '29506-3833',
 '29512-0611',
 '29526-5004',
 '29530-5202',
 '29536-1341',
 '29605-3550',
 '29605-5426',
 '29607-5223',
 '29609-3002',
 '29616-0357',
 '29625-5853',
 '29645-3237',
 '29650-4127',
 '29651-6627',
 '29657-0687',
 '29673-7717',
 '29673-8225',
 '29673-8906',
 '29684-9307',
 '29690-8013',
 '29708-8494',
 '29715-6942',
 '29715-9446',
 '29715-9761',
 '29720-8214',
 '29730-6330',
 '29745-0460',
 '29801-6320',
 '29801-9521',
 '29812-5710',
 '30004-3384',
 '30004-6725',
 '30016-4694',
 '30040-9655',
 '30043-5672',
 '30046-4550',
 '30047-3788',
 '30062-3661',
 '30066-1023',
 '30108-0280',
 '30115-8104',
 '30117-9601',
 '30144-5024',
 '30152',
 '30168-5540',
 '30168-7061',
 '30214-2236',
 '30228',
 '30281-2281',
 '30288-1115',
 '30296-6914',
 '30298-0307',
 '30316-2625',
 '30329-2004',
 '30336-2726',
 '30341',
 '30461',
 '30504-6006',
 '30506-3242',
 '30507-8450',
 '30513-6362',
 '30518-2615',
 '30549-1683',
 '30558-1827',
 '30607-1121',
 '30720-3467',
 '30904',
 '31023-8918',
 '31024-4410',
 '31024-8229',
 '3103',
 '31201-3485',
 '31405',
 '31405-5489',
 '31408-2931',
 '31601-4540',
 '31763-4938',
 '31794-4716',
 '32043-4955',
 '32044-4310',
 '32055-4319',
 '32055-6823',
 '32063-2028',
 '32064-4825',
 '32119-2183',
 '32127',
 '32128-6967',
 '32176-5789',
 '32210',
 '32211-7278',
 '32244',
 '32254-2014',
 '32259-3039',
 '32311-8749',
 '32315-4336',
 '32317-3622',
 '32336-7238',
 '32506-3229',
 '32535-2659',
 '32570-9696',
 '32607-1350',
 '32616-0160',
 '32703-7757',
 '32703-7794',
 '32707',
 '32707-3650',
 '32746-2139',
 '32751-5503',
 '32763',
 '32778-9123',
 '32779-5657',
 '32789-4529',
 '32792-2251',
 '32804-3401',
 '32807-3904',
 '32809-8531',
 '32810-4168',
 '32810-4340',
 '32811-1688',
 '32817-4176',
 '32824-8288',
 '32839-2771',
 '32904-1090',
 '32931-3399',
 '32940-7766',
 '32968-4953',
 '3301',
 '33012-7189',
 '33013-1360',
 '33014-3403',
 '33018-6703',
 '33019-5023',
 '33037-2921',
 '3304',
 '33054-4223',
 '33063-3050',
 '33064-1579',
 '33064-4325',
 '33127-3808',
 '33130-1209',
 '33147-3865',
 '33161-3436',
 '33161-7413',
 '33166',
 '33166-5454',
 '33166-6838',
 '33175-6894',
 '33177-3210',
 '33179-4308',
 '33301-1121',
 '33304',
 '33309-2676',
 '33312-1295',
 '33314-2103',
 '33314-3635',
 '33317-7339',
 '33334-4575',
 '33351-7338',
 '33403',
 '33404-5262',
 '33404-5456',
 '33407-1007',
 '33407-2383',
 '33426-2907',
 '33431-4403',
 '33431-6637',
 '33434-3953',
 '33436-5904',
 '33458-6024',
 '33463-3209',
 '33523-8659',
 '33556-2816',
 '33563-2805',
 '33597-4123',
 '33604-1234',
 '33604-4107',
 '33605-3225',
 '33609-3618',
 '33610',
 '33610-4102',
 '33611',
 '33614-5440',
 '33617-4248',
 '33619-3245',
 '33637-6781',
 '33701-4341',
 '33702-3015',
 '33709-1627',
 '33764-7257',
 '33765-3539',
 '33773-1656',
 '33778',
 '33778-1602',
 '33781-5913',
 '33801-9578',
 '33809-1706',
 '33813-4909',
 '33815-3342',
 '33823-8310',
 '33859-8288',
 '33868-9230',
 '33868-9746',
 '33881-1826',
 '33902-9343',
 '33903-1244',
 '33912-2042',
 '33950-6033',
 '33980-3052',
 '34205-6106',
 '34205-7629',
 '34221-8651',
 '34233-3464',
 '34238-2523',
 '34240-8643',
 '34240-9691',
 '34243-2112',
 '34286-9101',
 '34293-6554',
 '34429-4326',
 '34436-4692',
 '34442-4517',
 '34449-9452',
 '34475-1329',
 '34475-1630',
 '34475-2500',
 '34475-8873',
 '34683-5825',
 '34689-3954',
 '34761-3048',
 '34957-4109',
 '34957-6188',
 '34994-3989',
 '34997-5704',
 '35007-4812',
 '35023-5735',
 '35043-9005',
 '35044-3009',
 '35055-0336',
 '35055-8134',
 '35071-2588',
 '35080-7223',
 '35094-4057',
 '35094-7507',
 '35117-3108',
 '35121-2606',
 '35124-2021',
 '35126-4411',
 '35127',
 '35172-9248',
 '35173-1442',
 '35203-1534',
 '35206-5014',
 '35228-3004',
 '35243-5227',
 '35244-2286',
 '35404-0098',
 '35405-4428',
 '35473-2319',
 '35475-2562',
 '35475-3852',
 '35501-5446',
 '35501-8556',
 '35553-2533',
 '35601-0572',
 '35611-9134',
 '35633-1300',
 '35674-8701',
 '35759-1203',
 '35802-1851',
 '35816-1534',
 '35901-9434',
 '35904-4545',
 '35906-8944',
 '35950-0233',
 '35950-1162',
 '35951-5006',
 '36022-3405',
 '36033-5512',
 '36048-3509',
 '36067-6218',
 '36108-4732',
 '36109-4202',
 '36117-1956',
 '36201-8200',
 '36206-1171',
 '36251-4108',
 '36502-4931',
 '36507-6621',
 '36521-3071',
 '36604',
 '36606-3050',
 '36609-3055',
 '36867-7348',
 '37040-0006',
 '37058-5315',
 '37066-4122',
 '37068-1235',
 '37086-4180',
 '37087-1943',
 '37087-3361',
 '37122-3734',
 '37127-7571',
 '37138-2218',
 '37166-2502',
 '37167-4893',
 '37188-8213',
 '37210-2903',
 '37210-4626',
 '37211-2342',
 '37215-4115',
 '37303',
 '37311-5852',
 '37331-1322',
 '37343-3040',
 '37347-5406',
 '37408',
 '37421-2980',
 '37601-4218',
 '37618-2134',
 '37618-2953',
 '37643',
 '3766',
 '37660-5858',
 '37683-2012',
 '37686-0784',
 '37687-3486',
 '37716-4503',
 '37771-2002',
 '37830-7077',
 '37871-1177',
 '37886-3016',
 '37912-1346',
 '37912-3929',
 '37917-6973',
 '37917-7734',
 '37924-4312',
 '37934',
 '38002-4254',
 '38006',
 '3809',
 '38115',
 '38115-1504',
 '38116',
 '38116-4327',
 '38127',
 '38132-1202',
 '38134-6314',
 '38135-3022',
 '38137-2700',
 '38168-1251',
 '3820',
 '38261-5556',
 '38313-9335',
 '38340-7717',
 '38351-7695',
 '38375-2334',
 '38375-3241',
 '38464-6050',
 ...]

###"Phone"

In [ ]:
uniq_value("Phone")

sorted_unique("Phone")

There are 2684 different values in the Phone column

[0.0,
 602992557.0,
 2010001111.0,
 2012276544.0,
 2012654555.0,
 2013321222.0,
 2017030058.0,
 2017739022.0,
 2018434999.0,
 2032397733.0,
 2032569800.0,
 2032626266.0,
 2032652255.0,
 2032843863.0,
 2033309604.0,
 2033351346.0,
 2033756615.0,
 2033771850.0,
 2034638299.0,
 2035027007.0,
 2035224107.0,
 2036614430.0,
 2037873646.0,
 2039250363.0,
 2039610910.0,
 2052216290.0,
 2052980834.0,
 2053300009.0,
 2053393381.0,
 2053399872.0,
 2054256343.0,
 2054584458.0,
 2054837205.0,
 2054892795.0,
 2054919730.0,
 2055541659.0,
 2055563636.0,
 2055928638.0,
 2056081156.0,
 2056256431.0,
 2056317436.0,
 2056407026.0,
 2056553281.0,
 2056630300.0,
 2056789205.0,
 2056811695.0,
 2056850043.0,
 2056999696.0,
 2057441142.0,
 2057806060.0,
 2058333900.0,
 2059958622.0,
 2062445005.0,
 2062464002.0,
 2062857440.0,
 2064436499.0,
 2065223220.0,
 2065228002.0,
 2065339600.0,
 2065454400.0,
 2066292159.0,
 2066328736.0,
 2066732009.0,
 2067212730.0,
 2067297599.0,
 2068244171.0,
 2068703339.0,
 2072553392.0,
 2073245568.0,
 2074743472.0,
 2075494559.0,
 2075821662.0,
 2077826964.0,
 2078654330.0,
 2078728803.0,
 2079246867.0,
 2083974138.0,
 2084593032.0,
 2085280934.0,
 2085621319.0,
 2086729660.0,
 2087316005.0,
 2087457077.0,
 2087628080.0,
 2088520728.0,
 2094645299.0,
 2094671121.0,
 2097273322.0,
 2098584131.0,
 2102710688.0,
 2103990516.0,
 2105319666.0,
 2105909363.0,
 2105999149.0,
 2106619400.0,
 2106619560.0,
 2106693473.0,
 2109245948.0,
 2109452200.0,
 2124891841.0,
 2124967800.0,
 2128644060.0,
 2128748799.0,
 2136880068.0,
 2142671342.0,
 2143285161.0,
 2143309848.0,
 2143396266.0,
 2143398807.0,
 2143493847.0,
 2143526400.0,
 2143585131.0,
 2143723030.0,
 2145037329.0,
 2145527979.0,
 2146309898.0,
 2146322270.0,
 2146347115.0,
 2146370760.0,
 2146511573.0,
 2146603900.0,
 2146881071.0,
 2147442400.0,
 2148198020.0,
 2148271872.0,
 2148878949.0,
 2149050523.0,
 2149051022.0,
 2149433661.0,
 2152252551.0,
 2153211591.0,
 2153320500.0,
 2153389181.0,
 2153644804.0,
 2153653720.0,
 2156383600.0,
 2156396511.0,
 2156696786.0,
 2157239674.0,
 2157368860.0,
 2158318800.0,
 2158555565.0,
 2158625665.0,
 2162672646.0,
 2162673830.0,
 2162979280.0,
 2164407260.0,
 2165242400.0,
 2165392789.0,
 2165561832.0,
 2165669550.0,
 2165930211.0,
 2166517477.0,
 2168894666.0,
 2169611910.0,
 2172472410.0,
 2172804934.0,
 2173700308.0,
 2173830504.0,
 2175323838.0,
 2177530448.0,
 2177538326.0,
 2177643838.0,
 2178547866.0,
 2179322315.0,
 2182369341.0,
 2182816300.0,
 2183896691.0,
 2186856450.0,
 2188798034.0,
 2189273015.0,
 2192566103.0,
 2193627727.0,
 2194628856.0,
 2194760005.0,
 2196632131.0,
 2252093724.0,
 2252162333.0,
 2252728778.0,
 2252918953.0,
 2252918999.0,
 2292448001.0,
 2293824750.0,
 2294202044.0,
 2313316095.0,
 2315829100.0,
 2317394239.0,
 2317678586.0,
 2317881519.0,
 2318617223.0,
 2318733640.0,
 2318733675.0,
 2319320811.0,
 2342003918.0,
 2392814572.0,
 2394157673.0,
 2397318027.0,
 2405474241.0,
 2483322252.0,
 2483328326.0,
 2483341611.0,
 2483480400.0,
 2484746723.0,
 2485432141.0,
 2485770010.0,
 2485790946.0,
 2485859139.0,
 2486472313.0,
 2486508414.0,
 2486818304.0,
 2486850101.0,
 2486857477.0,
 2486932271.0,
 2512810414.0,
 2514461682.0,
 2514500607.0,
 2514786789.0,
 2515805091.0,
 2518665463.0,
 2524307368.0,
 2524912318.0,
 2525191111.0,
 2527479224.0,
 2527522266.0,
 2527961910.0,
 2528265605.0,
 2529464877.0,
 2529773333.0,
 2532929937.0,
 2533330313.0,
 2535205112.0,
 2535205124.0,
 2535367870.0,
 2535393587.0,
 2538450617.0,
 2538457607.0,
 2538526970.0,
 2538638782.0,
 2539222974.0,
 2539260891.0,
 2539272670.0,
 2539459900.0,
 2539463325.0,
 2539469247.0,
 2544421660.0,
 2545592100.0,
 2545844005.0,
 2545972767.0,
 2546945830.0,
 2548484300.0,
 2548763446.0,
 2548817253.0,
 2549337000.0,
 2549391565.0,
 2563542709.0,
 2563785430.0,
 2563839546.0,
 2564130939.0,
 2564927053.0,
 2565431236.0,
 2565687703.0,
 2567294113.0,
 2567395988.0,
 2567673705.0,
 2567737279.0,
 2567962108.0,
 2568203105.0,
 2568287906.0,
 2568355516.0,
 2568379511.0,
 2568781397.0,
 2568787341.0,
 2568788982.0,
 2568810315.0,
 2603550100.0,
 2603732010.0,
 2604329425.0,
 2604611113.0,
 2604787411.0,
 2604842371.0,
 2605623685.0,
 2605653177.0,
 2607244414.0,
 2607289168.0,
 2607495831.0,
 2608245576.0,
 2608332863.0,
 2622501445.0,
 2625677582.0,
 2625694075.0,
 2626280883.0,
 2626447530.0,
 2626620313.0,
 2626734077.0,
 2627030757.0,
 2627243346.0,
 2627845870.0,
 2628352070.0,
 2692169615.0,
 2693292582.0,
 2693498544.0,
 2693757008.0,
 2697812247.0,
 2697921250.0,
 2697923500.0,
 2697937537.0,
 2702744356.0,
 2703659017.0,
 2703954475.0,
 2704430113.0,
 2707334342.0,
 2707695772.0,
 2708698733.0,
 2708855632.0,
 2709262264.0,
 2766942121.0,
 2769444118.0,
 2813378782.0,
 2813535200.0,
 2813547777.0,
 2813621640.0,
 2813675252.0,
 2813709208.0,
 2814072749.0,
 2814150603.0,
 2814221029.0,
 2814371190.0,
 2814372014.0,
 2814414623.0,
 2814424537.0,
 2814454100.0,
 2814642800.0,
 2815167725.0,
 2815685556.0,
 2815922476.0,
 2816570837.0,
 2816890202.0,
 2819935451.0,
 3013362344.0,
 3014031500.0,
 3015727444.0,
 3015820640.0,
 3016382827.0,
 3016948550.0,
 3017023001.0,
 3017581177.0,
 3018161000.0,
 3018993108.0,
 3019299390.0,
 3019940748.0,
 3022272100.0,
 3023681500.0,
 3026524343.0,
 3026595722.0,
 3027623005.0,
 3028564060.0,
 3028756500.0,
 3029945191.0,
 3029983853.0,
 3032862684.0,
 3032872872.0,
 3033071892.0,
 3033999954.0,
 3034499112.0,
 3034552443.0,
 3034609900.0,
 3034661921.0,
 3034663536.0,
 3035243820.0,
 3035349966.0,
 3035369870.0,
 3036840351.0,
 3036937781.0,
 3037330071.0,
 3037522422.0,
 3037611245.0,
 3037619809.0,
 3037680881.0,
 3037720447.0,
 3037895427.0,
 3037980053.0,
 3038570450.0,
 3039333211.0,
 3042331500.0,
 3042338610.0,
 3042912280.0,
 3042921815.0,
 3043258534.0,
 3043420501.0,
 3043632070.0,
 3043693631.0,
 3043974397.0,
 3044728878.0,
 3045994195.0,
 3046592684.0,
 3046652020.0,
 3047449393.0,
 3052224297.0,
 3052899288.0,
 3053627283.0,
 3053789527.0,
 3054063879.0,
 3055124726.0,
 3055575042.0,
 3055927504.0,
 3056356889.0,
 3056871717.0,
 3056911900.0,
 3057693919.0,
 3057927661.0,
 3058221632.0,
 3058921412.0,
 3058990808.0,
 3059787374.0,
 3072650809.0,
 3083844701.0,
 3085327730.0,
 3086320812.0,
 3096523189.0,
 3096887506.0,
 3097645999.0,
 3097974188.0,
 3097997746.0,
 3098635759.0,
 3098884477.0,
 3098978456.0,
 3099328220.0,
 3102972671.0,
 3103134343.0,
 3103309909.0,
 3103607300.0,
 3103737279.0,
 3104349850.0,
 3104717777.0,
 3105168490.0,
 3105320404.0,
 3105780500.0,
 3106579699.0,
 3106591711.0,
 3106629931.0,
 3106703064.0,
 3107790526.0,
 3107982310.0,
 3108263420.0,
 3108295800.0,
 3109213337.0,
 3127265766.0,
 3134862593.0,
 3135065547.0,
 3135310400.0,
 3137316733.0,
 3139085246.0,
 3139085247.0,
 3142220515.0,
 3142665230.0,
 3143556999.0,
 3143932123.0,
 3145030734.0,
 3145246000.0,
 3146313443.0,
 3147037004.0,
 3147313027.0,
 3147380323.0,
 3147714785.0,
 3147738866.0,
 3149931330.0,
 3152453113.0,
 3152532891.0,
 3153345424.0,
 3153632813.0,
 3154224806.0,
 3154227561.0,
 3154372577.0,
 3154631950.0,
 3154849218.0,
 3154888080.0,
 3156332059.0,
 3156525794.0,
 3156763406.0,
 3156952485.0,
 3158668789.0,
 3159637718.0,
 3162631819.0,
 3162837301.0,
 3164442483.0,
 3165292005.0,
 3166832931.0,
 3167124082.0,
 3172090099.0,
 3172400500.0,
 3172711207.0,
 3172803051.0,
 3172911500.0,
 3172957056.0,
 3172972177.0,
 3172996066.0,
 3173481394.0,
 3173502619.0,
 3173776950.0,
 3173871500.0,
 3174623124.0,
 3174811626.0,
 3174860260.0,
 3175353500.0,
 3175358232.0,
 3175395765.0,
 3175789188.0,
 3175903221.0,
 3176147471.0,
 3176240555.0,
 3177273161.0,
 3177331506.0,
 3177848185.0,
 3177869300.0,
 3177872291.0,
 3177873113.0,
 3178132998.0,
 3178240113.0,
 3178467400.0,
 3178521408.0,
 3178524411.0,
 3178527121.0,
 3178527171.0,
 3178588900.0,
 3178700007.0,
 3178722700.0,
 3178924100.0,
 3178949533.0,
 3184439563.0,
 3186404112.0,
 3187487481.0,
 3187578346.0,
 3193516551.0,
 3193647000.0,
 3194624550.0,
 3195452137.0,
 3195452212.0,
 3196432277.0,
 3198871083.0,
 3202355591.0,
 3202522323.0,
 3202537355.0,
 3202563001.0,
 3202746617.0,
 3202748874.0,
 3203522051.0,
 3205682381.0,
 3207322181.0,
 3207634545.0,
 3207634740.0,
 3207952827.0,
 3212549228.0,
 3216745003.0,
 3217837096.0,
 3232213448.0,
 3235875101.0,
 3236381869.0,
 3236711300.0,
 3239380191.0,
 3252354624.0,
 3256030652.0,
 3256434295.0,
 3256769379.0,
 3256770474.0,
 3302732142.0,
 3303420001.0,
 3304200463.0,
 3304354713.0,
 3304538900.0,
 3304563267.0,
 3304572354.0,
 3304778506.0,
 3304988444.0,
 3305338943.0,
 3305495313.0,
 3306770680.0,
 3306881225.0,
 3307021999.0,
 3307221150.0,
 3307583425.0,
 3307987744.0,
 3308211133.0,
 3308334003.0,
 3308786630.0,
 3308987063.0,
 3309314583.0,
 3309740992.0,
 3342309938.0,
 3342665955.0,
 3342772610.0,
 3342794822.0,
 3342978787.0,
 3343563424.0,
 3343586050.0,
 3343769423.0,
 3362269416.0,
 3362291878.0,
 3362412255.0,
 3362726336.0,
 3363745058.0,
 3363760506.0,
 3363772727.0,
 3364311004.0,
 3364316824.0,
 3364342075.0,
 3364632455.0,
 3364754042.0,
 3364758498.0,
 3364760100.0,
 3364987964.0,
 3364988213.0,
 3365384941.0,
 3366236942.0,
 3366628870.0,
 3367313747.0,
 3367668402.0,
 3367668549.0,
 3368510639.0,
 3368511600.0,
 3368870917.0,
 3368872222.0,
 3368874221.0,
 3368876110.0,
 3369080643.0,
 3369572666.0,
 3369733131.0,
 3369733155.0,
 3369924691.0,
 3372335593.0,
 3372340557.0,
 3372565212.0,
 3373646065.0,
 3376684411.0,
 3394995928.0,
 3478252274.0,
 3479336518.0,
 3523328210.0,
 3523433884.0,
 3523444329.0,
 3523511140.0,
 3523695095.0,
 3523716294.0,
 3524374860.0,
 3524477009.0,
 3524682196.0,
 3525832974.0,
 3526375143.0,
 3526713406.0,
 3527327600.0,
 3527959234.0,
 3602992528.0,
 3603070001.0,
 3603302886.0,
 3604241234.0,
 3604794112.0,
 3604797801.0,
 3605249679.0,
 3605741159.0,
 3606683328.0,
 3606713021.0,
 3606714794.0,
 3606914562.0,
 3606958582.0,
 3606972700.0,
 3607243824.0,
 3608160211.0,
 3608762563.0,
 3612759977.0,
 3612890026.0,
 3612892298.0,
 3612932311.0,
 3613563407.0,
 3615754569.0,
 3618542007.0,
 3618848248.0,
 3863645184.0,
 3867558646.0,
 3867677530.0,
 3867745522.0,
 3867889002.0,
 3869513042.0,
 4012287557.0,
 4012447214.0,
 4012742114.0,
 4014150030.0,
 4016477742.0,
 4017625544.0,
 4017820001.0,
 4018210579.0,
 4022281596.0,
 4022930140.0,
 4024472200.0,
 4024668388.0,
 4024758836.0,
 4024776060.0,
 4024897156.0,
 4024945904.0,
 4024948118.0,
 4025334667.0,
 4025654425.0,
 4025823410.0,
 4028919200.0,
 4029351939.0,
 4042498919.0,
 4043207106.0,
 4043498355.0,
 4043638860.0,
 4043665121.0,
 4045200808.0,
 4046227772.0,
 4048761048.0,
 4052125424.0,
 4052473095.0,
 4052580957.0,
 4052600001.0,
 4052734759.0,
 4052822727.0,
 4053503373.0,
 4053723925.0,
 4054477788.0,
 4054958787.0,
 4056064000.0,
 4056343577.0,
 4056723329.0,
 4057280634.0,
 4057878789.0,
 4057900477.0,
 4057990644.0,
 4058131932.0,
 4058436117.0,
 4058675569.0,
 4058786666.0,
 4059125800.0,
 4059422159.0,
 4059693883.0,
 4062278183.0,
 4062457451.0,
 4062542400.0,
 4062785944.0,
 4062933415.0,
 4064342983.0,
 4064423400.0,
 4064665375.0,
 4066520628.0,
 4066557575.0,
 4066562054.0,
 4066824805.0,
 4067239556.0,
 4072072133.0,
 4072402202.0,
 4072981358.0,
 4072981818.0,
 4072985010.0,
 4074280116.0,
 4074641744.0,
 4076280039.0,
 4076471940.0,
 4076548890.0,
 4076710909.0,
 4076780055.0,
 4076955526.0,
 4077712000.0,
 4077887212.0,
 4078308801.0,
 4078526380.0,
 4078861963.0,
 4082494149.0,
 4082678164.0,
 4082750500.0,
 4082921607.0,
 4082957611.0,
 4083744617.0,
 4083747303.0,
 4083777707.0,
 4083781935.0,
 4083967859.0,
 4084578359.0,
 4086001788.0,
 4087270430.0,
 4087470149.0,
 4087964467.0,
 4088478732.0,
 4089456410.0,
 4093851841.0,
 4097942768.0,
 4098668593.0,
 4102281884.0,
 4102423700.0,
 4102722252.0,
 4103607700.0,
 4103645072.0,
 4104897309.0,
 4105262811.0,
 4105481098.0,
 4105757124.0,
 4105835682.0,
 4106438444.0,
 4106617799.0,
 4106617950.0,
 4106653929.0,
 4107124290.0,
 4107561500.0,
 4107680665.0,
 4107780131.0,
 4107962277.0,
 4108605559.0,
 4122690088.0,
 4123660382.0,
 4123844822.0,
 4129283250.0,
 4132770658.0,
 4134679073.0,
 4135366572.0,
 4135674342.0,
 4136506941.0,
 4137460610.0,
 4144458965.0,
 4144463729.0,
 4144750404.0,
 4144834900.0,
 4152472883.0,
 4154569868.0,
 4155247216.0,
 4156210500.0,
 4156261135.0,
 4156420273.0,
 4172562767.0,
 4172567982.0,
 4172728585.0,
 4173256200.0,
 4173353063.0,
 4173580682.0,
 4174437002.0,
 4174518888.0,
 4174852898.0,
 4175818786.0,
 4175884497.0,
 4176242900.0,
 4176672287.0,
 4176737426.0,
 4176793834.0,
 4177672364.0,
 4177821976.0,
 4178319898.0,
 4178657135.0,
 4178667495.0,
 4178771995.0,
 4178826437.0,
 4178868557.0,
 4179354999.0,
 4179624734.0,
 4179673730.0,
 4192582100.0,
 4192862495.0,
 4193558980.0,
 4193823011.0,
 4193947178.0,
 4193966829.0,
 4194332003.0,
 4194489551.0,
 4194696207.0,
 4194761600.0,
 4194766252.0,
 4194781101.0,
 4195296145.0,
 4195299499.0,
 4195399415.0,
 4195850070.0,
 4196258697.0,
 4196262256.0,
 4196689369.0,
 4198251652.0,
 4198365070.0,
 4198651970.0,
 4198670600.0,
 4198863775.0,
 4232089128.0,
 4232637482.0,
 4232886948.0,
 4233910971.0,
 4234721981.0,
 4234822140.0,
 4235070005.0,
 4235381075.0,
 4235386799.0,
 4235428113.0,
 4237275636.0,
 4237724692.0,
 4238370124.0,
 4238422855.0,
 4238929560.0,
 4239265317.0,
 4239520883.0,
 4242420030.0,
 4252282277.0,
 4252679199.0,
 4253084321.0,
 4253335600.0,
 4253489826.0,
 4253532287.0,
 4253555050.0,
 4254381970.0,
 4254530901.0,
 4254857017.0,
 4255130501.0,
 4256447849.0,
 4257437720.0,
 4258350623.0,
 4323321706.0,
 4323373717.0,
 4325631700.0,
 4342936306.0,
 4343926666.0,
 4344767038.0,
 4345258263.0,
 4345460783.0,
 4346857353.0,
 4347242904.0,
 4347368491.0,
 4348227200.0,
 4348227700.0,
 4348227999.0,
 4348366818.0,
 4348457590.0,
 4349297613.0,
 4349857658.0,
 4352777223.0,
 4356281896.0,
 4357239428.0,
 4357832933.0,
 4358651862.0,
 4402017543.0,
 4402341188.0,
 4402557338.0,
 4402850886.0,
 4402858467.0,
 4403245248.0,
 4403270840.0,
 4404994906.0,
 4406350495.0,
 4408160407.0,
 4409539386.0,
 4693844903.0,
 4695692441.0,
 4697069851.0,
 4783743017.0,
 4787850650.0,
 4792540006.0,
 4796360737.0,
 4796462004.0,
 4796466351.0,
 4797509404.0,
 4797700088.0,
 4798243829.0,
 4799687000.0,
 4802698021.0,
 4802698022.0,
 4802851600.0,
 4803324300.0,
 4803770552.0,
 4808168003.0,
 4808272252.0,
 4808990788.0,
 4809511962.0,
 4809643488.0,
 4809664787.0,
 4809669887.0,
 4809915320.0,
 4809984300.0,
 4842562101.0,
 4843283671.0,
 5012188701.0,
 5012683530.0,
 5012688277.0,
 5012689999.0,
 5013274410.0,
 5013622927.0,
 5014507000.0,
 5014550612.0,
 5016663351.0,
 5016792311.0,
 5016796559.0,
 5019451550.0,
 5019851711.0,
 5022671899.0,
 5023968751.0,
 5024474881.0,
 5024596292.0,
 5024995777.0,
 5025386803.0,
 5028452105.0,
 5028962832.0,
 5032087637.0,
 5032319694.0,
 5032565384.0,
 5032852269.0,
 5032885735.0,
 5033038580.0,
 5033251957.0,
 5033991664.0,
 ...]

###"Direct Phone"

In [ ]:
uniq_value("Direct Phone")

sorted_unique("Direct Phone")

There are 836 different values in the Direct Phone column

[' 618-271-3000',
 '#ERROR!',
 '(014) 286-8290',
 '(074) 972-1144',
 '(203) 330-9604',
 '(205) 987-6518',
 '(206) 949-0922',
 '(209) 727-3322',
 '(209) 993-0680',
 '(210) 702-2220',
 '(212) 496-7800',
 '(214) 379-6600',
 '(214) 413-9965',
 '(214) 637-0760',
 '(214) 905-1022',
 '(216) 267-2646',
 '(216) 524-2400',
 '(218) 281-6300',
 '(219) 932-8067',
 '(230) 601-8888',
 '(231) 861-7223',
 '(239) 215-6110',
 '(256) 236-7635',
 '(256) 280-2131',
 '(256) 740-5100',
 '(256) 878-4390',
 '(301) 694-8550',
 '(301) 816-1000',
 '(302) 629-3553',
 '(303) 752-2422',
 '(303) 880-4627',
 '(305) 769-3919',
 '(309) 888-4477',
 '(314) 524-6000',
 '(317) 299-6066',
 '(317) 727-3161',
 '(317) 852-1408',
 '(317) 852-7171',
 '(317) 858-3717',
 '(317) 872-2700',
 '(330) 453-8900',
 '(360) 691-4562',
 '(405) 533-4675',
 '(405) 624-3214',
 '(407) 275-3200',
 '(407) 275-3200 ext. 4319',
 '(407) 588-7857',
 '(407) 661-1114',
 '(407)275.3200',
 '(412) 318-3000',
 '(419) 258-2100',
 '(419) 355-8980',
 '(419) 448-9551',
 '(423) 538-1075',
 '(434) 822-7700',
 '(435) 277-8000',
 '(435) 277-8024',
 '(435) 901-0218',
 '(440) 635-0495',
 '(480) 285-1600',
 '(480) 718-6105',
 '(480) 745-8446',
 '(480) 816-8003',
 '(480) 998-4300',
 '(501) 258-4266',
 '(501) 679-2311',
 '(502) 326-8413',
 '(503) 285-7667',
 '(503) 351-7818',
 '(505) 345-9935',
 '(508) 336-6588',
 '(509) 326-4485',
 '(513) 983-1100',
 '(530) 448-3694',
 '(541) 728-2524',
 '(561) 988-3600',
 '(562) 404-7211',
 '(562) 404-7237',
 '(562) 404-7267',
 '(570) 490-2413',
 '(585) 247-0260',
 '(585) 352-5590',
 '(602) 263-6011',
 '(602) 263-6011 ext 605125',
 '(602) 263-6011 x691148',
 '(602) 263-6012',
 '(602) 263-6561',
 '(602) 263-6681 x621130',
 '(602) 274-3471',
 '(602) 277-5207',
 '(603) 718-3781',
 '(614) 529-7000',
 '(615) 860-9888',
 '(618) 624-6400',
 '(630) 978-9897',
 '(631) 425-1555',
 '(636) 285-4311',
 '(636) 600-4600',
 '(651) 466-0212',
 '(703) 504-8288',
 '(704) 453-2038',
 '(704) 455-3400',
 '(704) 662-0039',
 '(704) 662-6600',
 '(704) 788-7811',
 '(704) 799-8977',
 '(706) 232-7793',
 '(706) 612-9500 logo',
 '(707) 252-2339',
 '(708) 388-5277',
 '(713) 271-9645',
 '(714) 639-7325',
 '(717) 334-7121',
 '(717) 766-8000',
 '(719) 667-0343',
 '(760) 598-7121',
 '(760) 746-0400',
 '(763) 785-6900',
 '(765) 364-0828',
 '(775) 356-1956',
 '(781) 293-5005',
 '(785) 841-0102',
 '(800) 336-9029',
 '(800) 407-5776',
 '(800) 468-4285',
 '(800) 524-1848',
 '(800) 528-0463',
 '(800) 530-9494',
 '(800) 541-0134',
 '(800) 570-2225',
 '(800) 733-1200',
 '(800) 787-8763',
 '(800) 827-7692',
 '(800) 839-0650',
 '(805) 583-8880',
 '(806) 535-1377',
 '(813) 962-1100',
 '(815) 933-5770',
 '(816) 220-4608',
 '(816) 224-7399',
 '(817) 893-8128',
 '(818) 341-7223',
 '(828) 692-4525',
 '(847) 465-8837',
 '(847) 674-6980',
 '(847) 678-3450',
 '(855) 983-7088',
 '(858) 677-5363',
 '(859) 408-2000',
 '(859) 408-2000 x119',
 '(860) 7996541',
 '(863) 661-3166',
 '(866) 411-5285',
 '(866) 490-9643',
 '(877) 675-9221',
 '(888) 458-9215',
 '(888) 596-8132',
 '(888) 651-1932',
 '(888) 814-5985',
 '(909) 469-6171',
 '(909)469.6171',
 '(916) 372-8037',
 '(920) 471-4099',
 '(920) 654-1063',
 '(925) 825-2099',
 '(940) 855-4051',
 '(949) 275-1222',
 '(949) 646-6086',
 '(951) 278-3799',
 '(951) 699-7800',
 '(954) 522-9900',
 '(970) 581-8134',
 '(978) 343-4210',
 '(989) 883-3382',
 '+1 (702) 873-2222',
 '+1 (714) 545-4100',
 '+1 (801) 465-1337',
 '+1 205-942-5708',
 '+1 262-275-5050',
 '+1 405-624-3214',
 '+1 415-252-0133',
 '+1 480-285-1600',
 '+1 602-263-6011',
 '+1 602-263-6841',
 '+1 704 455 3400',
 '+1 704-453-2803',
 '+1 818-610-3956',
 '+1.301.779.5756',
 '+1.317.299.6066',
 '+1.317.872.2700',
 '+1.503.774.3203',
 '+1.510.656.2200',
 '+1.602.263.6011',
 '+1.602.263.6011 x 612188',
 '+1.618.548.9011',
 '+1.630.655.0200',
 '+1.704.453.2038',
 '+1.704.453.2894',
 '+1.704.455.0644',
 '+1.704.455.3400',
 '+1.775.688.6300',
 '+1.888.733.2505',
 '+1.902.454.8533',
 '+1.941.371.9383',
 '+1.952.854.2044',
 '+1.954.733.2505',
 '+39 06 6504 7519',
 '+44 20 7287 9776',
 '+54 11 4257-0983',
 '+57(318)381-1660',
 '-2364',
 '.405.624.3214',
 '.603.889.1166',
 '.615.515.5400',
 '.615.515.5402',
 '.615.515.5426',
 '.615.515.5430',
 '.617.588.0083',
 '.617.588.2185',
 '.989.435.7080',
 '01 42 86 8',
 '020 89695888',
 '1 (602) 263-6011',
 '1 905 889 5400',
 '12032167244',
 '12075227347',
 '12198015865',
 '12706173165',
 '13035884834',
 '13172506316',
 '13174037055',
 '13174579643',
 '13179185140',
 '13179795794',
 '14072474736',
 '14077459732',
 '14127263057',
 '14804608800',
 '16107036537',
 '16109994045',
 '17046779757',
 '17328955790',
 '18037275171',
 '18123509972',
 '18165196091',
 '18165502600',
 '19136691987',
 '19416855671',
 '19515520195',
 '19737654375',
 '1|614|843-2147',
 '2.14E+11',
 '2012657808',
 '2018434999',
 '2032843863',
 '2033338804',
 '2053450284',
 '2055928638',
 '2056630300',
 '2058333900',
 '2058414450',
 '2058416749',
 '206-390-8173',
 '2063908173',
 '2075494559',
 '2078654330',
 '2079246867',
 '2083222730',
 '2102962306',
 '2123408635',
 '2123408667',
 '2123408822',
 '2125323200',
 '2146312620',
 '2147446705',
 '2148192500',
 '2148796113',
 '215-569-4060',
 '2153576600',
 '2157236277',
 '2157239674',
 '2158318800',
 '2158620608',
 '216-447-0013',
 '2162317300',
 '2162673830',
 '2165242400',
 '2182369341',
 '2188245454',
 '2189273015',
 '229-382-4750',
 '2293824752',
 '2315823114',
 '2394157673',
 '2485770010',
 '2486508414',
 '2514332792',
 '2514500607',
 '2524307368',
 '2525238003',
 '2529773333',
 '2563839546',
 '2566201429',
 '2567737279',
 '2568448656',
 '2568788982',
 '2604611774',
 '2607495831',
 '2625694069',
 '2625694075',
 '2625696450',
 '2626447530',
 '2626620313',
 '2626734077',
 '2627805357',
 '2697921250',
 '2697923500',
 '27222924',
 '2766942121',
 '2766943239',
 '2769444118',
 '2813547777',
 '3014909888',
 '3018161000',
 '3033393001',
 '3034426754',
 '3039043400',
 '3042921815',
 '3043420501',
 '3055003726',
 '3056356889',
 '3092439020',
 '3098884477',
 '310-657-9699',
 '3105320404',
 '3106150311',
 '3106579699',
 '3123071332',
 '3129662554',
 '3132552960',
 '3133822242',
 '3135924200',
 '3135925238',
 '3143556999',
 '3147313027',
 '3147732547',
 '3154224806',
 '3154631950',
 '3154849218',
 '3172400500',
 '3172911500',
 '3172996066',
 '3174623124',
 '3174811626',
 '3175395765',
 '3177873113',
 '3178949533',
 '3178959111',
 '3207952827',
 '3216745003',
 '32479951336',
 '3304200463',
 '3304538900',
 '3305337000',
 '3305495313',
 '3306300270',
 '3306522277',
 '3307698300',
 '3308690837',
 '3342794822',
 '3343586050',
 '3362412255',
 '3364311004',
 '3364760100',
 '3367668402',
 '3368874221',
 '3373679937',
 '3378557830',
 '3602930619',
 '3602934587',
 '3602938488',
 '3606972700',
 '3608160211',
 '3609443350',
 '3615754569',
 '3618818885',
 '3862283113',
 '4025968616',
 '403-209-3325',
 '4043665121',
 '4045275730',
 '4048761048',
 '4056064475',
 '4057878789',
 '4057994444',
 '4059428827',
 '406-728-7600',
 '4066772080',
 '4066824805',
 '4072753200',
 '4072981358',
 '4072985010',
 '4073397211',
 '4075857000',
 '4076280039',
 '4076548890',
 '4076710909',
 '4078308801',
 '4082750500',
 '4087322500',
 '4089561526',
 '4105431880',
 '4106434606',
 '4106617950',
 '412-318-3000',
 '4129283250',
 '4143535850',
 '4152529766',
 '4156542919',
 '4156770909',
 '4173343633',
 '4173353063',
 '4179354999',
 '419-836-5070',
 '4193558980',
 '4194702552',
 '4194781101',
 '4198365070',
 '4233910971',
 '4235386799',
 '4238215317',
 '4323373717',
 '4344768238',
 '4348227200',
 '4348227700',
 '435-277-8000',
 '435-783-2933',
 '4358671865',
 '436678793',
 '4400000000',
 '4408011802',
 '4408160407',
 '4408885104',
 '4698534691',
 '472864853',
 '4796466351',
 '4799678352',
 '480-383-9279',
 '480.351.8135',
 '4805329002',
 '4806094300',
 '5024596292',
 '5024912660',
 '5032474622',
 '5032857667',
 '5036637200',
 '5037361823',
 '5038721436',
 '5058635089',
 '5062285138',
 '5072632471',
 '5072810304',
 '5073742261',
 '5082780020',
 '5082783980',
 '5086501600',
 '5087753700',
 '5087957830',
 '5088221655',
 '5088359292',
 '5088543100',
 '5089840005',
 '5089927404',
 '5093264485',
 '5106577874',
 '5107641570',
 '5122505046',
 '5122582282',
 '5135311881',
 '5137321152',
 '5137723233',
 '5153821616',
 '5159934248',
 '5164896550',
 '5168872600',
 '5169316901',
 '5184343300',
 '5185625708',
 '5187318497',
 '5187472945',
 '5302231179',
 '5592531928',
 '5616978729',
 '5618402109',
 '5618422492',
 '5618443938',
 '5618480673',
 '5626929331',
 '5629448982',
 '5633862902',
 '5634453624',
 '5635842622',
 '5635842636',
 '5704511600',
 '5733342839',
 '5736860330',
 '5737323541',
 '585-924-1870',
 '6.29E+11',
 '6013522607',
 '6022556200',
 '6022636627',
 '6033299318',
 '6035795208',
 '6037427817',
 '6038757575',
 '6038869300',
 '6038891166',
 '6039266005',
 '6053956401',
 '6064746850',
 '6077648514',
 '6082585580',
 '6082585588',
 '6082585591',
 '6082688116',
 '6082688129',
 '6088843363',
 '6094665305',
 '6095568765',
 '61 8 9355 8100',
 '6107740224',
 '6129887108',
 '6142384000',
 '6142611541',
 '6144786626',
 '6145297000',
 '6145297013',
 '6145297014',
 '6152552890',
 '6152595525',
 '6154442487',
 '6155973160',
 '6162817503',
 '6163647054',
 '6163949533',
 '6165388020',
 '617-588-0152',
 '6184761221',
 '6202254155',
 '6202772367',
 '6203458798',
 '6262502276',
 '6264424018',
 '6269144761',
 '6307535000',
 '6308607077',
 '6314251555',
 '6314679040',
 '6316860400',
 '6318411846',
 '6364583997',
 '6415283685',
 '6417243220',
 '6503409473',
 '6503437107',
 '6505435600',
 '6512279509',
 '6514559775',
 '6514640092',
 '6608267199',
 '6612546120',
 '6613237831',
 '6617645456',
 '662-349-4300',
 '6782845320',
 '7012939798',
 '7014543891',
 '7032226198',
 '7032570600',
 '7038230202',
 '704-455-3400',
 '704-664-2300',
 '7042021827',
 '70436671',
 '7043791414',
 '7043995626',
 '7044550312',
 '7044550384',
 '7044553400',
 '7044553801',
 '7044553896',
 '7044561220',
 '7044561221',
 '7044829506',
 '7045099550',
 '7045255889',
 '7045350030',
 '7045367785',
 '7045925554',
 '7046386863',
 '7046580940',
 '7046626222',
 '7046626811',
 '7046629570',
 '7046632311',
 '7046642300',
 '7046648115',
 '7046648180',
 '7047842500',
 '7047991118',
 '7047998326',
 '7047998341',
 '7047998348',
 '7048828000',
 '7049249404',
 '7049479696',
 '7058872277',
 '706-337-9900',
 '7064858506',
 '7065431797',
 '707-252-2339',
 '7074373366',
 '7088653333',
 '7123666440',
 '7127923864',
 '713 8630400',
 '7136760677',
 '7136787066',
 '7136971043',
 '7146390329',
 '7146880288',
 '7153429150',
 '7164871570',
 '7172437855',
 '7172490455',
 '7172666966',
 '7177664300',
 '7179388732',
 '7182565500',
 '7185426026',
 '7186809020',
 '7188588466',
 '7189948300',
 '7193369014',
 '720-277-3788',
 '7208512700',
 '7243274020',
 '7249255000',
 '7275330503',
 '7318852344',
 '7322713463',
 '7326340330',
 '7327800770',
 '7345857036',
 '740-397-4969',
 '7403350318',
 '7403497610',
 '7403532066',
 '7403974969',
 '7406713030',
 '7407542299',
 '7574615040',
 '760-758-6100',
 '7607479947',
 '7634414070',
 '7652897567',
 '7654824273',
 '7656898727',
 '7702978772',
 '7706192253',
 '7708470554',
 '7709245088',
 '7758520606',
 '7758842332',
 '7813963500',
 '7814477933',
 '7853577222',
 '7854342717',
 '7858627106',
 '7858627158',
 '7858996543',
 '8.21E+11',
 '8002239223',
 '8003394516',
 '8004683785',
 '8006348598',
 '8007702055',
 '8009942816',
 '8009992438',
 '8012953741',
 '8017826125',
 '8026555929',
 '8035321011',
 '8035483113',
 '8038177056',
 '805-434-2963',
 '8054669261',
 '8063766273',
 '8106799847',
 '81260355721',
 '8128767788',
 '813-465-7455',
 '8133165571',
 '8138732333',
 '8143546340',
 '8145873811',
 '8146423000',
 '8146433000',
 '8146433003',
 '815-657-8400',
 '8155778504',
 '8156292418',
 '8156784017',
 '8156784949',
 '8157252727',
 '8159335770',
 '816-224-7303',
 '816-627-4941',
 '8162294400',
 '8163538900',
 '8164540711',
 '8164544200',
 '8164557779',
 '8165454200',
 '8166274919',
 '8166274999',
 '8166907555',
 '8167773349',
 '8167774233',
 '8167958055',
 '8168470474',
 '8168618833',
 '8169234404',
 '8169235000',
 '8172613169',
 '8172992254',
 '8173266109',
 '8175571200',
 '8176253307',
 '8176267090',
 '818-338-7232',
 '818-519-6743',
 '8183417223',
 '8188870136',
 '8284538044',
 '8284652600',
 '8286832734',
 '8286833037',
 '8286920191',
 '8286924525',
 '8434880865',
 '8473078753',
 '8474658837',
 '8476746716',
 '8476746980',
 '8504539248',
 '8563098808',
 '8568632861',
 '8592241926',
 '8592602624',
 '8592763546',
 '8592789241',
 '8592931663',
 '8602730123',
 '8603553761',
 '8606842783',
 '8609537637',
 '8636613166',
 '8639676864',
 '8642209370',
 '8642771268',
 '8644598009',
 '8645820038',
 '8648341516',
 '8654700027',
 '8663590636',
 '8666051307',
 '8707934441',
 '9.73E+11',
 '9013969288',
 '9014529663',
 '9045377278',
 '9047711639',
 '9047728592',
 '9083224291',
 '9083552600',
 '9088628856',
 '909-469-6171',
 '9093578542',
 '9094332812',
 '910-899-0604',
 '910-947-5309',
 '913-362-7111',
 '9133270013',
 '9133340307',
 '9177497646',
 '9182587223',
 '9194600288',
 '9194811600',
 '9203245300',
 '9204620350',
 '9207872656',
 '9257362773',
 '9312689546',
 '9373905848',
 '9407677694',
 '9416273339',
 '9417275740',
 '9513690384',
 '9518264166',
 '9524452759',
 '9524751335',
 '9525441679',
 '9544747997',
 '9547848010',
 '9547979242',
 '9562678830',
 '9566874046',
 '9703525550',
 '9721400015',
 '9722765121',
 '9724094307',
 '9724772951',
 '9724857441',
 '9724872830',
 '9724872835',
 '9724872876',
 '9724872883',
 '9724872900',
 '9725577557',
 '9727315271',
 '9735757750',
 '9898938299',
 'Andrews',
 '\\+1.602.263.6011']

###"Contact First", "Contact Last", "Title", "Address", "Company Name", "Website" and "Email" not for considering